### ISSUE TITLE
Information about Homebrew's task "Handle formula renames and deletions"

### ISSUE THREAD

**Issue by youtux** [github/gsoc#10]
@mikemcquaid I am very interested in the Homebrew's tasks, but I have a question about "Handle formula renames and deletions": is it necessary to use Git to handle the renaming or is feasible to use some kind of migration file that keeps track of formulae renaming?

**Comment by MikeMcQuaid** [comment]
@youtux I'm open to either approach. The migration files have worked well for tap migrations so might be a good fit for here too.

**Comment by youtux** [comment]
Thank you!
