### ISSUE TITLE
Octokit.Net running on .NET Core

### ISSUE THREAD

**Issue by shana** [github/gsoc#100]
## Before you start

**Please read the student manual at http://write.flossmanuals.net/gsocstudentguide/what-is-google-summer-of-code/ and make sure you understand how the program works, how proposals are submitted and all the milestones involved.**

Head to the relevant issues linked below to discuss the project, ask your questions, etc. If you’re looking for entry tasks to get up to speed with the project, there are plenty of issues available labeled “easy-fix” in the repository, go ahead and grab one!

---

**About Octokit.Net**

[Octokit.Net](octokit.net) is the [open source](https://github.com/octokit/octokit.net) cross-platform GitHub API Client Library for .NET.

**Summary**

Octokit.Net currently runs on .NET 4.5, Mono 3.x, Xamarin.iOS / Xamarin.Android / Xamarin.Mac and Windows 8 / 8.1 Store Apps. We would love to have it running on .NET Core as well!

**Skills**: C#

**Relevant issues**:
- https://github.com/octokit/octokit.net/issues/1115
- https://github.com/octokit/octokit.net/issues/832

**Mentors**: @shiftkey

**Comment by devkhan** [comment]
I want to learn more about hits project, is there chat or discussion forum for this?

**Comment by rogertinsley** [comment]
:+1: for this, if I can contribute then I'd be happy to do so.

**Comment by M-Zuber** [comment]
@devkhan there is a gitter chat. The README should have a link to it.

**Comment by shiftkey** [comment]
This effort has commenced by members of the Octokit community.
