### ISSUE TITLE
Octokit.Net - Rewrite HTTP internals

### ISSUE THREAD

**Issue by shana** [github/gsoc#101]
## Before you start

**Please read the student manual at http://write.flossmanuals.net/gsocstudentguide/what-is-google-summer-of-code/ and make sure you understand how the program works, how proposals are submitted and all the milestones involved.**

Head to the relevant issues linked below to discuss the project, ask your questions, etc. If you’re looking for entry tasks to get up to speed with the project, there are plenty of issues available labeled “easy-fix” in the repository, go ahead and grab one!

---

**About Octokit.Net**

[Octokit.Net](octokit.net) is the [open source](https://github.com/octokit/octokit.net) cross-platform GitHub API Client Library for .NET.

**Summary**

One of our favourite bits of Octokit is how we take away all the hassles of configuring the HTTP stack, and for the most part it works. But every now and again, people hit up upon limitations with our setup - and you have to re-implement HttpClientAdapter to get to these features, and navigate a lot of the Octokit plumbing which isn't great.

We'd like to improve on this and create an API that moves as much of the HTTP setup out of Octokit's core as possible, so that consumers have more control over the HTTP interactions, and also leverage the existing abstractions for HttpClient and HttpMessageHandler more broadly, so that Octokit can benefit from the extensibility in the .NET framework.

**Skills**: C#, Octokit.Net

**Relevant issues**
https://github.com/octokit/octokit.net/issues/1116
https://github.com/octokit/octokit.net/issues/984
https://github.com/octokit/octokit.net/issues/985

**Mentors**: @shiftkey

**Comment by devkhan** [comment]
I want to learn more about this project, is there a chat or forum etc.?

**Comment by AlexP11223** [comment]
Hi.

I am a student and I am looking for a project for GSoC. I have experience in web and desktop development (including .NET).
I live in Europe, UTC+2.

I think this project may be suitable for me. How should I start? What should I do before application?

**Comment by shana** [comment]
Heads-up: I've updated the issue with important information about the project and GSoC in general, please make sure you read the information linked.

**Comment by devkhan** [comment]
@shana Can you please tell about some resources/issues from where to understand how Octokit.Net works from the inside, how is it structured, etc?

I am new to the project and hence, would first like to gain some insight about the project and jumping on to the mentioned issues/PRs later on. :bow:

**Comment by shana** [comment]
@devkhan You should go to the project repo and figure those things out by cloning and building the project, looking at the tests and the code, reading the documentation, etc. There are links to the relevant issues above where you can ask questions.

**Comment by devkhan** [comment]
Thanks @shana, I think I'm gonna do some research before continuing and working on the proposal.

**Comment by devkhan** [comment]
@shiftkey Can you please tell us at what times will you be available on chat or email or GitHub Issues? I live in India (UTC+5:30). I will adjust my timing according to yours.

**Comment by johndbritton** [comment]
@devkhan We started a chat room here: https://gitter.im/github/mentorships

**Comment by devkhan** [comment]
@johndbritton I know, I opened that issue but I just thought that since issues are such a major part of GitHub workflow, it would be better if I posted on this issue.

Anyway, thanks. :+1:
