### ISSUE TITLE
Atom Community Representative

### ISSUE THREAD

**Issue by lee-dohm** [github/gsoc#103]
Provide day-to-day support and services to the Atom community through Issues, Pull Requests, discussion forum and other support channels. This is designed as an entry-level opportunity for someone who wants to get involved in the tech industry.

**Heads Up!** _this mentorship is not available for GSoC_
### Expected Outcome

Candidate has an understanding of and capability to perform:
- Issue and PR triage according to Atom's current flow
- Add or update documentation
- Reproduce Issues and write full repro steps
- Interfacing with a large and demanding open source community in a consistently positive manner on a wide variety of technical issues
### Skills
- Candidate must be able to communicate clearly in the English language in various written forms: chat, message board, Twitter, etc.
- Candidate must have familiarity with computers, installing/uninstalling software, and using the web
### Mentors
- @lee-dohm

**Comment by lee-dohm** [comment]
/cc @bkeepers

Totally open to feedback on tightening this proposal up or making it more clear.

**Comment by johndbritton** [comment]
This looks pretty cool, but just want to make it clear that this one would not be eligible for GSoC.

**Comment by lee-dohm** [comment]
@johndbritton Yes, that's correct.

**Comment by devkhan** [comment]
Is this open to students? 
I do understand the duties and responsibilities but is this like a job or something or can anyone who is well versed with GitHub workflow, especially Atom's) do it (remotely)?

**Comment by lee-dohm** [comment]
Sorry @devkhan for not getting back to you on this right away. This is a new kind of mentorship role for us, so there are still some things we need to figure out. I'll be updating here when we have more information :grinning:

**Comment by jmarlena** [comment]
Hey @lee-dohm!  I am really excited about this idea. I am wondering what's the timeline or next steps for this?

**Comment by hackerkid** [comment]
@lee-dohm I am also interested in this. Would love to know more. :sparkles:

**Comment by equinox** [comment]
@lee-dohm Any potential updates on this?

**Comment by lee-dohm** [comment]
This is something we're still pursuing and working on. We don't have anything to share right now or an ETA on when we will have something public. For now, I'm going to close this and reopen it when we have an update. It's something that we're really excited about and I'm personally working pretty hard on, there's just a lot to work out :grinning: Thanks everyone for your patience. If you're interested in this, please subscribe here for updates and I'll let you all know as soon as I have something!

@Equinox Thanks for following up.
