### ISSUE TITLE
Jekyll community plugin and theme directory

### ISSUE THREAD

**Issue by benbalter** [github/gsoc#105]
### Summary

Similar to Atom's https://atom.io/packages, this project would create an interactive directory to help maintainers showcase and users discover Gem-based Jekyll themes and plugins.
### Expected Outcome

An open source, community-maintained site at `plugins.jekyllrb.com` and `themes.jekyllrb.com` (or `jekyllrb.com/plugins` and `jekyllrb.com/themes`) that lists community-maintained Jekyll plugins and themes, with a showcase page for each plugin/theme, and a mechanism by which plugin and theme authors can add and update their project's listing.
### Skills

This could be implemented entirely in Jekyll, such that mentees would require only basic knowledge of HTML, CSS, and liquid/Jekyll templating, or could be implemented as a dynamic server, which could be implemented in any web-publishing framework, but preferably Ruby.
### Relevant issues

There is some prior art in https://github.com/jekyll/plugins, https://jekyllrb.com/docs/plugins/, http://www.jekyll-plugins.com/, http://jekyllthemes.org/, and http://jekyllthemes.io/. 
### Mentors

@benbalter, @parkr

**Comment by prastut** [comment]
Hi @benbalter this project looks lovely. Where can I discuss this project? Email or here?

**Comment by benbalter** [comment]
@prastut awesome to hear! Glad to chat here, if you don't mind the conversation being public, otherwise, you can email opensource@github.com and mention this issue, and we can chat privately.

**Comment by hackerkid** [comment]
@benbalter Thanks for adding this project. The Jekyll community has been waiting for an official directory for a long time.

**Comment by prastut** [comment]
@benbalter, @parkr  No problem in the discussion being public. This comment would help other potential first time GSOCer's too who aren't familiar with the GSOC process.

Jekyll is something which I have been using extensively in my projects and passionate about. I am currently in the phase of porting [my website](http://prastut.github.io/) and was interning with a [startup](https://www.houseafic.com) which used Jekyll heavily for templating, Parse for backend, Github for server, since Jekyll interfaces with it very well, and Js (JQuery) too tie them all together. The experience of creating a minimum fully functioning viable product without spending a cent was amazing and the team could utilize that much more time/money on separate issues like business etc.
- About brainstorming the project, questions are as follows:
  - Since this project would heavily depend upon design, I would want the dialog or focus to be on it. Correct me if I am wrong. I looked through the links you have given and found the following:
    - I think the design should stem for Jekyll's original website therefore would want to extend it. Personally I love the use of low tones like brown, black with yellow. Though we could do with some lighter tones too. Mockups and wireframes would be needed to be approved first.
    - Atom's package website though is simple but it caters to people who know the specific package's name (people can hack their way around). But that's not the case with the user-base of Jekyll.
      - First we need to define the user-base of Jekyll. I think Jekyll is majorly used by bloggers and people who need a easy solution for static templating without the need of going to Js templating solutions like Handlebars, EJS etc.
    - Therefore all the more need for brainstorming the UX for this:
      - There should be easy categories which should be linked to the plugin.
      - The search would therefore be of much importance and unlike the Atom's website, the results should be in the form of autocomplete. 
        - More importance on needcase rather than package. Atom plugins website categorizes plugins with featured, trending, and updated but the importance should be more on need-case. 
        - Github like nifty hacks in search: use-case, labels, hashtag etc.
    - On the plugin page:
      - Similar to what we have on http://www.jekyll-plugins.com/ , the plugin's should have it's GitHub aggregation data. 
      - A GIF explaining what the plugin does as given on Atom's page.
      - Right now I felt there is work in installing the plugin. We could brainstorm a process to reduce the friction. Something like Sublime plugins, you search->enter->install with a readme. I haven't used a Jekyll plugin firsthand, never felt the need too, therefore I might be wrong on this front. 

I also wanted to know your view point and expectations on this project. You obviously want to increase Jekyll's user-base through plugins but is the vision limited to that? I asked this question since this project seems to be in my comfort zone and I found #108 more interesting in terms of the learning curve. 

It becomes mandatory for me to ask this question:
- How would you evaluate a candidate's potential to bring this project home? 
  - I understand that you will look for past contributions. Haven't been contributing to Jekyll in specific though - [x]
  - Could you guide me to relevant bugs and issues to complete to prove my proficiency?

**Comment by benbalter** [comment]
@prastut all great questions. 

> I think the design should stem for Jekyll's original website therefore would want to extend it. Personally I love the use of low tones like brown, black with yellow. Though we could do with some lighter tones too. Mockups and wireframes would be needed to be approved first.

That sounds like a good approach. While neither @parkr nor I are designers, GitHub has some talented designers (many of whom are also Jekyll users), that I'm sure can also lend a hand.

> Atom's package website though is simple but it caters to people who know the specific package's name (people can hack their way around). But that's not the case with the user-base of Jekyll.... First we need to define the user-base of Jekyll. 

That's a great observation, and while I linked out to Atom's package website as an example, it's important  to distinguish the two projects, and their users bases, as you did. While Atom's a text editor, and thus many of its users are developers that don't mind getting their hands dirty, I suspect many Jekyll users just want an easy-to-maintain website and don't want to be overly bothered by the internals. I think your suggestion to focus on use case, have categories/tags, and to optimize for installation/use, etc. is a good approach (although, extending Jekyll's command line interface, to e.g. `jekyll install some-plugin` would be beyond the scope of this project).

> I also wanted to know your view point and expectations on this project. You obviously want to increase Jekyll's user-base through plugins but is the vision limited to that? I asked this question since this project seems to be in my comfort zone and I found #108 more interesting in terms of the learning curve.

There's definitely a desire to grow and strengthen the Jekyll ecosystem. There's a lot of great plugins and themes out there, but it's often hard to find the right one, meaning their not used as much as they otherwise might be, and thus they also see fewer contributions. There's also a desire to improve the experience of existing Jekyll users. A plugin is a lot easier (and often produces better results) than solving common problems one off, and reduces the learning curve for creating your first site. Last, it will also serve as a great, central place to showcase the vibrancy of the Jekyll community, and all the different (and interesting) things that are possible with Jekyll.

> I understand that you will look for past contributions. Haven't been contributing to Jekyll in specific though

A candidate doesn't necessarily have to have Jekyll experience, and your design thinking above is a great example of that. It may help to be familiar with other plugin/theme ecosystems (e.g., WordPress), or project/plugin relationships in other open source projects. It's also not too late! Jekyll's got a gentle learning curve, and is a very approachable, intuitive code base. Consider [making your first contribution](https://github.com/jekyll/jekyll/blob/contributing-refresh/CONTRIBUTING.markdown) this week to get a better feel for the Jekyll community.

> Could you guide me to relevant bugs and issues to complete to prove my proficiency?

In addition to the links above, I'd also point you towards https://github.com/jekyll/jekyll/issues/4510, which will implement better-packaged themes, much like plugins are distributed today.

**Comment by erlend-sh** [comment]
@parkr is [jekyll/plugins](https://github.com/jekyll/plugins) still relevant? Could it be used as a starting point for the student?

**Comment by parkr** [comment]
@erlend-sh Yes, jekyll/plugins is still relevant. As a starting point, we can use the content from http://jekyllrb.com/docs/plugins/#available-plugins, normalize the fields, and present the packages on plugins.jekyllrb.com or jekyllrb.com/plugins.

**Comment by prastut** [comment]
@benbalter @parkr I wish to discuss this project more. Can I make some wireframes and send it across?

**Comment by benbalter** [comment]
> Can I make some wireframes and send it across?

Of course! Looking forward to discussing them. :smile_cat:

**Comment by daviddarnes** [comment]
What's the current status on this? I've been experimenting with gem based Jekyll themes and I'm really liking is so far. I'd like get onboard with it in some way 😄

**Comment by benbalter** [comment]
@daviddarnes we'd still very much like to see this, but in terms of GitHub mentorships, we don't currently have any [available programs](https://github.com/github/mentorships/labels/program).

**Comment by daviddarnes** [comment]
@benbalter that's fine, I was replying to this as I followed it from related issues to the Jekyll themes integration. Maybe this should be a new topic on [talk.jekyllrb.com](https://talk.jekyllrb.com)? Then we can see what direction the community wants to take? 💭

**Comment by MikeMcQuaid** [comment]
GitHub is not participating directly in GSoC 2017. The Homebrew project (which I maintain) has applied to participate this summer: https://github.com/Homebrew/Outreachy-and-Google-Summer-of-Code. Note you'll need access to a Mac to take part. Thanks!
