### ISSUE TITLE
Internationalization / localization support for Jekyll

### ISSUE THREAD

**Issue by benbalter** [github/gsoc#106]
### Summary

Most modern web-publishing frameworks support the ability to publish content in multiple languages. Doing so for static sites presents a unique challenge. This project would create a core Jekyll plugin to enable web publishers to localize static content (e.g., `example.com/en/about` versus `example.com/es/about`).
### Expected outcome

A Jekyll plugin that allows web publishers to publish content in a primary language, define alternate translations, and publish that same content in multiple languages, falling back to the untranslated content, where no translation is available.
### Skills

This project will require basic Ruby knowledge, as Jekyll is written in Ruby. Prior experience with internationalization or localization in other frameworks, as well as speaking a non-English language, would be helpful, but not required. 
### Relevant issues

There's prior art in https://github.com/octopress/multilingual, https://github.com/github/choosealicense.com/pull/131, https://github.com/jekyll/jekyll/issues/1809, and https://github.com/incompl/jekyll-localize
### Mentors

@parkr, @benbalter

**Comment by Calinou** [comment]
I would like to work on this. I'm a native French speaker and also use Jekyll quite a bit (I have used it for an university project).

**Comment by AlexanderEkdahl** [comment]
Another way of splitting content is by using different cTLDs for content(google.kr, google.se, google.com, etc.) which is the method recommended by Google. I've hacked on Jekyll before and not sure if that is outside the scope of Jekyll as it would probably require splitting the output into different destination folders.

Internationalization presents many unique challenges such as RTL, date and time formats, list ordering, etc. While I don't think Jekyll should have built-in functionality for all these scenarios it should be at least possible to properly make internationalized websites which handles the different cases.

This is something I would also love to work with as I'm currently living in country where I don't understand the language and very few websites are localized...

In combination with #97

**EDIT:** On a second thought splitting content by TLD would never work with GitHub Pages which is probably the most popular usecase for Jekyll

**Comment by ismnoiet** [comment]
@benbalter  This is interesting, and  i have 1 question : 

Is it the publisher who add the translated version or it is generated automatically ?.

Thanks.

**Comment by benbalter** [comment]
> Is it the publisher who add the translated version or it is generated automatically ?.

@ismnoiet Awesome to hear. It would be the publisher who would translate the content. Hope you consider applying!

**Comment by ismnoiet** [comment]
thanks @benbalter  for the response and I'll do my best to apply.

**Comment by an0sunshy** [comment]
What suggestions would you give to an applicant who has little or zero experience in localization and internationalization?

**Comment by ismnoiet** [comment]
@soulboyx  just use [google](https://google.com) and [stackoverflow](https://stackoverflow.com)
i'm sure you'll find interesting articles and topics about internationalization.

Good luck :).

**Comment by clintonb** [comment]
Additional prior art: https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin.

**Comment by hardlyhuman** [comment]
I am interested in working on this. I know French, Spanish and german to some extent.  And I have a basic knowledge in Ruby too.

**Comment by MikeMcQuaid** [comment]
GitHub is not participating directly in GSoC 2017. The Homebrew project (which I maintain) has applied to participate this summer: https://github.com/Homebrew/Outreachy-and-Google-Summer-of-Code. Note you'll need access to a Mac to take part. Thanks!
