### ISSUE TITLE
GUI/Administrative interface for Jekyll

### ISSUE THREAD

**Issue by benbalter** [github/gsoc#107]
### Summary

This project would create a traditional CMS-style graphical / interactive interface (think WordPress's `wp-admin` section) to author static content and administer Jekyll sites. This could be a generic WYSIWYG markdown editor for static sites, or a purpose built tool for non-command-line users to administer their Jekyll site.
### Expected Outcome

The project would result in a desktop application, or easy-to-run web server, that would allow less-traditionally-technical Jekyll site maintainers to more easily author Markdown content for static sites and/or administer their Jekyll site, such as creating new posts, adding collections, and modifying post-specific and site-wide settings.
### Skills

This project can go in several different directions. Mentees can build the project entirely in Ruby, as a web server, that users would access via their browser (e.g., `localhost:4000/admin`). This would require traditional Ruby web development skills, and knowledge of how to write files to read and write files to and from disk using Ruby. It can also take the form of a stand-alone application, such as one using Electron, or a Atom plugin, both of which would require knowledge of Node, and the ability to read/write file to/from disk in Node.
### Relevant issues

http://prose.io, https://talk.jekyllrb.com/t/visual-editor-for-jekyll/1055, https://chrome.google.com/webstore/detail/jekyll-editor/dfdkgbhjmllemfblfoohhehdigokocme?hl=en, and https://atom.io/packages/markdown-writer, https://atom.io/packages/jekyll.
### Mentors

@benbalter, @parkr

**Comment by mertkahyaoglu** [comment]
Really cool project :sparkles: I would love to work on it.

**Comment by erlend-sh** [comment]
Prior art:

https://github.com/gabriel-john/utterson (discuss [here](https://talk.jekyllrb.com/t/backend-web-interface-for-jekyll/1712))
https://github.com/rlafranchi/statixite
https://github.com/netlify/netlify-cms

**Comment by hackerkid** [comment]
This project is awesome. I would also love to work on it :zap:

**Comment by dinever** [comment]
Pretty cool project. BTW you guys can refer to this one. https://github.com/jaredly/hexo-admin.git

**Comment by hackerkid** [comment]
@benbalter @parkr I mailed to opensource@gh regarding this project three days before. I didn't get a reply yet.  Should I mail you guys to your personal mail or wait some more time for the reply?

 Since the application period is opening soon I would love to hear your feedback before submitting the proposal.

**Comment by benbalter** [comment]
> I mailed to opensource@gh regarding this project three days before. I didn't get a reply yet. Should I mail you guys to your personal mail or wait some more time for the reply?

@hackerkid Glad to see you're excited, and thanks for your patience over the weekend. I just replied with some high-level feedback.

**Comment by hackerkid** [comment]
@benbalter Thanks a lot for the feedback. I will make changes as you suggested.

**Comment by arrowrowe** [comment]
Hi, mind asking the current progress here? Didn't find much information in [Jekyll's repo](https://github.com/jekyll/jekyll) (by searching inside it) or @hackerkid's public activities.

**Comment by benbalter** [comment]
@arrowrowe the project is still a proposed idea. I suspect the above discussion was largely part of [the Google Summer of Code Application process](https://developers.google.com/open-source/gsoc/).

**Comment by arrowrowe** [comment]
@benbalter got it. Thanks for the response!

**Comment by Sneezry** [comment]
Here's a project I wrote last year, and published just now.

https://github.com/JekyllWriter/JekyllWriter

![71ec0c97jw1ez0vgutjqtj21a00z0ae1](https://cloud.githubusercontent.com/assets/1621293/14008805/6f94f0c6-f1c0-11e5-868d-4ef0e182667b.jpg)

**Comment by rebornix** [comment]
@Sneezry currently it's more or less a Writer, you can make it a real administrator application :+1:

**Comment by Sneezry** [comment]
@rebornix Yeah, I'll try to do it :)

**Comment by rush-skills** [comment]
Hey @benbalter . I would love to work on this project for GSoC'16. I have sent a mail to you and @parkr with some ideas and would love your feedback.

**Comment by hackerkid** [comment]
@Sneezry Thanks for sharing the project.

**Comment by benbalter** [comment]
🎉  See https://github.com/jekyll/jekyll-admin.
