### ISSUE TITLE
create an official github android application

### ISSUE THREAD

**Issue by keon** [github/gsoc#109]
I discovered that github applications in androids are all privately made and they are maintained poorly.
I wish to make github experience available anywhere on smartphones.

**Comment by bkeepers** [comment]
Hi @keonkim, thanks for the suggestion! 

Little known fact: there used to be an [official Android app](https://github.com/blog/1187-github-android-app-released)! [PocketHub](https://github.com/pockethub/PocketHub) that was originally written by GitHub's own @kevinsawicki. It didn't get enough usage for us to continue putting a lot of resources into it, so we handed it over to the community.
