### ISSUE TITLE
Prospective GSoC 2016 student

### ISSUE THREAD

**Issue by Dragooon** [github/gsoc#110]
Hello!

To begin with, I'm not really sure if creating an issue is appropriate, if there is some other way I should get in touch with mentors, please let me know. 

I’m Shitiz Garg, a third year computer science student from India and a freelance web developer primarily focussing on PHP/JS. This would be my third GSoC, during my first and second year I participated with phpBB and Drupal respectively but this year I’m looking to move slightly away from PHP, perhaps into full stack JS (node.js) or something similar.

Any suggestions, starting points, guidelines, ideas I should pursue or anything else would be appreciated. Thank you!

**Comment by johndbritton** [comment]
You can view the list of projects on this repository and find one that looks interesting to you. From there you should be able to go to the project itself and get a look at some starter issues or get a conversation going with potential mentors via the channels they use for communication for their project.
