### ISSUE TITLE
Atom - Project Idea for GSOC

### ISSUE THREAD

**Issue by Aakash1312** [github/gsoc#111]
For Gsoc, I have thought of the following project ideas:
I am presently searching for mentor for any of these topics.

**a. Implementing a new decoration type and marker layer for scrollbar**

Refs. atom/find-and-replace/issues/529 and atom/atom/issues/9120
Markers on scrollbar can give a very good insight of the entire document. Scrollbar takes a very little space of text-editor. But with its help, we can go through the entire document. Therefore, it can be used to convey useful information.

Some of the uses of scrollbar markers are :
1. It can be used to give an eagle’s eye view of find-and-replace markers for a better analysis of search results.
2. It can be used to represent Git-diff. Users can quickly identify where the code has been added, deleted or changed.
3. Scroll-bookmarks : It might have occurred to you that while working on a file, you want to visit some block of code again and again. The only way this can be possible is by remembering the starting line number of that block of code. But instead of that, we can bookmark the line on scroll-bar and we are done!

Besides this, I think there are various ways in which these scrollbar markers can be utilized.

_Some implementation details:_

Unlike most other markers, scrollbar markers are a bit different in a way that they don't need a range of numbers (unlike find-and-replace markers where you have to specify starting point and ending point of the found word) but a single number is required to make a scrollbar-marker. This single number can represent the distance of marker from the top or bottom of the scrollbar.
In order to find this number, we require three things:
- _The row number_ of the point which is presented by scrollbar marker.
  For this we can introduce new methods, namely, markScreenRow and markBufferRow in text-editor-marker-layer file
- _Scroll-height:_
  For this we can use getScrollHeight function provided by text-editor-presenter.coffee and also in text-editor.coffee
- _Present display height:_
  Display height denotes the portion of the screen which is visible. We can get present height  using height variable of display-buffer.coffee

There are various complications involved. For example, unlike ordinary markers, scrollbar markers can change with change in display height of text editor. Hence a mechanism has to be introduced to keep track of the changes taking place in display height. 
One possible way of handling this problem is by subscribing to onDidUpdateState function of text-editor-presenter.coffee.
Besides, there is problem of how to represent marker in HTML DOM. One possible way of representation is by using HTML element line <li>. These line elements will be contained in a parent node which will overlap the scrollbar domnode.

**b. Synchronize data with cloud storage like Google Drive, OneDrive, Dropbox, etc.**

Cloud storage provides a very good medium to share data. What if we bring the same functionality to text editors? Sharing of code can become much more easier if the cloud interface is present in the text-editor itself.
_Implementation details:_
- The project basically employs use of various APIs provided by cloud services. Since Atom is written in coffeescript, the javascript version of these APIs can be potentially used (Some changes may be required)
- Another step in building the project is OAuth. Atom shell can be used to get OAuth token to access cloud services.
- APIs provide many details of cloud storage files. These details have to be processed to make a proper directory structure in GUI. Google Drive API, however, does not provide proper file paths, so making a proper directory structure for google drive may be troublesome.

**c. The concept of active subscriptions**

While working with find-and-replace package, I figured out that markers are destroyed and recreated each time text-editor is changed (i.e. switching tabs). 
Well I might be wrong, but still I would like to put my proposal.
I figured out that there is only one marker layer, i.e., resultMarkerLayer dedicated to find-and-replace markers.  By tweaking with the visibility of different markers, we can make this layer contain markers from multiple buffers. Hence, when switching the tab, markers will not be destroyed and recreated, rather only their visibility is changed.
One problem with this approach is leaking subscriptions. Once an object is created, it's subscription will always remain active until or unless the subscriptions are disposed (and hence object is destroyed).
What my suggestion is to add an additional feature to subscription API, i.e., active and inactive subscription.
Only active subscriptions should respond to changes happening in buffer. In this way, we won't need to dispose off the subscriptions every time we don't need them. Simply deactivating subscriptions for the time being can simplify things a lot.

**Comment by iolsen** [comment]
Hi Aaakash. There are some really cool ideas here but unfortunately the Atom team has limited mentorship bandwidth this summer and we're not going to be able to help with this. Thanks for your interest in Atom!
