### ISSUE TITLE
Octokit.net - add support for lookup by repository ID throughout APIs

### ISSUE THREAD

**Issue by shiftkey** [github/gsoc#112]
## Before you start

Please read the student manual at http://write.flossmanuals.net/gsocstudentguide/what-is-google-summer-of-code/ and make sure you understand how the program works, how proposals are submitted and all the milestones involved.

Head to the relevant issues linked below to discuss the project, ask your questions, etc. If you’re looking for entry tasks to get up to speed with the project, there are plenty of issues available labeled “easy-fix” in the repository, go ahead and grab one!

---

**About Octokit.Net**

Octokit.Net is the open source cross-platform GitHub API Client Library for .NET.

**Summary**

The GitHub API supports looking up repositories by owner and name, but a secondary API exists which supports looking up repositories by their numeric ID. As repositories are a key feature of the GitHub API, adding support for this will flow through a significant part of the codebase and involve a number of core components.

**Skills:** C#, Octokit.Net

**Relevant issues**
https://github.com/octokit/octokit.net/issues/1120

**Mentors:** @shiftkey

**Comment by nikibobi** [comment]
Hi, I'm interested in this project for GSoC. I have C# experience and I think I can handle this task. I have also developed a simple C# API wrapper for Pastebin in the past.

**Comment by shiftkey** [comment]
@nikibobi welcome - please have a read of the related issue and also the work involved with [writing a proposal](http://write.flossmanuals.net/gsocstudentguide/writing-a-proposal/) - applications are now open!

**Comment by shiftkey** [comment]
This was completed as part of GSoC 2016! :tada:
