### ISSUE TITLE
Classroom - Usage dashboard

### ISSUE THREAD

**Issue by johndbritton** [github/gsoc#115]
_Aside from the projects listed here, we are open to other proposals and ideas. Take a look at issues labeled [feedback](https://github.com/education/classroom/labels/feedback), [feature-request](https://github.com/education/classroom/labels/feature-request), [enhancement](https://github.com/education/classroom/labels/enhancement), and [help-wanted](https://github.com/education/classroom/labels/help-wanted) for ideas._

About Classroom:

[Classroom for GitHub](https://classroom.github.com) is an [open source](https://github.com/education/classroom) tool for managing programming coursework on GitHub. The app enables teachers to distribute starter code to students, automatically creating repositories and managing access control for students. It also provides teachers with an easy way to get an overview of their students' submissions made on GitHub.

Summary:

Classroom is centered on GitHub organization accounts, users, repositories, and teams. In it's current state, there's no easy way for administrators to get a view into the usage of the application. The goal of this project is to implement a dashboard as part of the `stafftools` to view usage statistics. Things like numbers of organizations, and the activity levels of organizations would be useful

Expected Outcome:
- A standardized way to present charts and graphs in the dashboard
- A dashboard for viewing a quick overview of application usage
- In-depth dashboards for a number of key metrics that should be determined by the student
- A way to control dashboard displays by date range

Skills: Ruby, Rails, RSpec, Testing, HTML, CSS, JavaScript

Relevant issues:
https://github.com/education/classroom/issues/356

Primary mentors:
- @johndbritton
- @tarebyte

Supporting mentors:
- @mkcode
- @jasonlong

**Comment by oparley** [comment]
@johndbritton @tarebyte 
What kind of metrics would you like to see on the dashboard? Do you already collect those metrics or do you want us to implement it?

**Comment by johndbritton** [comment]
> What kind of metrics would you like to see on the dashboard?

Part of the project is figuring out what's useful and proposing to create it. There are two main goals for this project:
1. Staff should be able to get an overview of activity appwide
2. Teachers should be able to get an overview of activity in their classrooms

> Do you already collect those metrics or do you want us to implement it?

The DB has a lot of data, but I think we'll also have to use the GitHub API for things like commit activity on repositories.

**Comment by oparley** [comment]
@johndbritton Thank you very much!

**Comment by gweennnnn** [comment]
Hi @johndbritton @tarebyte Is there a list of things that are being stored/recorded in the database already, such as the day students accept the assignments/the day the classroom was made? It would give a better idea of what can be done using existing data!

**Comment by cyhsutw** [comment]
Hi @johndbritton @tarebyte 

I took a look at the DB schemas of `classroom` and try to brainstorm the metrics we can present to the site admins and teachers:

### For Site Admins
- Count of resources as mentioned in [education/classroom#356](https://github.com/education/classroom/issues/356)
- Associations between resources:
  - Average #users per organization
  - Average #assignments per organization
  - Average #groupings per organization
  - Average #users per group
  - Average #assignments per user
  - ...
- Activity level:
  - Organizations that do not create any new assignments in the past {some time interval}.
  - Organizations that do not have any repo activity in the past {some time interval} (may achieve this using GitHub API).
  - Assignments (those accepted by users) that do not have any repo activity in the past {some time interval}.
  - ...

All of these can be viewed with a specific time window.

### For Teachers
- General
  - #students (count of unique user_ids under an organization).
  - #repos related to a specific assignment (e.g. 27 students/groups have started working on `Swift-LinkedList`).
  - Latest commit and its timestamp of assignment repos.
  - ...
- Group Assignments Specific
  - The proportion of contributions by each group members (but this might be a costly operation for large classes).
  - ...
  
  I've been teaching assistants for several courses in our university, in my opinion, these metrics are really helpful for me to evaluate the performance of students.

This is just a small set of metrics we can derive from the data, there are lots of potentials of this project.

Thank you for reading this :bowtie:

Cheng-Yu

**Comment by johndbritton** [comment]
> s there a list of things that are being stored/recorded in the database already, such as the day students accept the assignments/the day the classroom was made

@gweennnnn You can take a look at [`schema.rb`](https://github.com/education/classroom/blob/master/db/schema.rb) to get an idea of what the DB structure looks like.

**Comment by babhishek21** [comment]
Is this project idea available for **GSOC '17**?

**Comment by tarebyte** [comment]
@babhishek21 unfortunately we're not taking on any GSOC students for the Classroom project this summer.

Thank you for your interest though!

**Comment by babhishek21** [comment]
@tarebyte No problem. Is this situation limited to the Classroom project, or are other GitHub projects not participating as well?

**Comment by tarebyte** [comment]
> Is this situation limited to the Classroom project, or are other GitHub projects not participating as well?

I don't believe so no, as far as I know GitHub is still participating in GSOC '17
