### ISSUE TITLE
Open Source for Computer Science education

### ISSUE THREAD

**Issue by nalasbali** [github/gsoc#117]
Hi all,

I would like to invite you to participate in my PhD research which is about contributing to Open Source to modernize Computer Science education. The survey will take few minutes but will be of great value to my research as i need direct evidences from OS communities like you, plz. 
I hope you will be happy to participate by clicking on the link below & feel free to answer any number of questions (will be much help if you can answer all):

Here you are the link to the mentor's survey: https://www.surveys.unsw.edu.au/f/161600/2b06/

Many thanks in advance,,
Nada Alasbali
PhD of Computer Science & Engineering, UNSW

**Comment by bkeepers** [comment]
Hey Nada, This isn't really the right venue for this type of content. Good luck on your research.
