### ISSUE TITLE
Any node.js project available here?

### ISSUE THREAD

**Issue by abdulhannanali** [github/gsoc#118]
I am a node developer and don't feel like I have anything to contribute to the Jekyll and Ruby projects here.. :smile:

**Comment by bkeepers** [comment]
Hi @abdulhannanali, thanks for getting in touch! We don't have any mentorships available with node at the moment, but keep an eye on this repository for more opportunities.

In the mean time, you might want to check out [@atom issues labeled "help-wanted"](https://github.com/search?utf8=%E2%9C%93&q=org%3Aatom+label%3Ahelp-wanted+is%3Aopen&type=Issues&ref=searchresults) for ways you could contribute to @atom, which is based on Node.

**Comment by abdulhannanali** [comment]
Hey @bkeepers! 
Thanks a lot I will definitely keep an eye on this repo. :+1: 
I will also check out @atom as it's a cool text editor and other cool projects too. :smile:
