### ISSUE TITLE
about 'Improve printing support of Atom Shell'

### ISSUE THREAD

**Issue by lincleejun** [github/gsoc#12]
first I'm not one of GSOC member, but I'm interesting about this.

so how could I start this? or couldn't
what  have you done?
what need be done?

@zcbenz thanks...

**Comment by johndbritton** [comment]
There's an issue: https://github.com/atom/atom/issues/3525 and also a discussion in the Atom forum: https://discuss.atom.io/t/printing-support/760 with some background.
