### ISSUE TITLE
About the hypermedia idea of Hub

### ISSUE THREAD

**Issue by shanzi** [github/gsoc#13]
After skimmed over the source code of go-octokit and some related material, I found the key problem makes the client not eligible may stands in Golang's characteristic of static typing. 

Lack of meta programing seems not only lead to code redundancy, but also prevents the implementation of a general library that can be used for other APIs.

But as soon as I see the word _hypermedia_, I thought of a very similar thing: _hyper json schema_ ([a good article about it](https://brandur.org/elegant-apis)) . Tool chains around hyper json schema are rich and it also has some abilities to define nested restful resource.

In fact, there already exists a Go library that translates hyper json schema into API client in Golang: [Schematic](https://github.com/interagent/schematic). It has been used by the heroku's fast CLI client [hk](https://github.com/heroku/hk) as the generator of API agent.

I guess [Schematic](https://github.com/interagent/schematic) may not be a good solution for [Hub](https://github.com/github/hub) because of the following problems:
1. Hyperlinks is predefined in hyper json schema other than response to what the API gives, so it is not as flexible
2. The protocol generated is not compatible with go-octokit and migration means a lot of modification of [Hub](https://github.com/github/hub)
3. Lack of API discoverability

But I still regard hyper json schema a good choice and maybe generated go code (with some tweak) is better than current hand writing redundantly code.

So, is it acceptable to transform go-octokit from human writing to generated? Maybe at first a generated client with exactly same interface and generally changed to one with more elegant protocol along with Hub?

BTW: I still have some other elementary ideas but I'm not sure is it suitable to discuss them in a public place like issues. Maybe email in private is better?

**Comment by johndbritton** [comment]
@mislav is probably the best person to answer this question.

**Comment by bkeepers** [comment]
@technoweenie, @rubyist, or @pengwynn may have some advice too.

**Comment by shanzi** [comment]
Hi! There seems isn't any advice yet?

I have had more consideration and formed a more mature idea now. I'm wondering if I should still discuss it here or contact the mentor @mislav in privately?

**Comment by bkeepers** [comment]
Hi @shanzi, sorry for the delay in responding. I think @mislav is traveling this week. 

It sounds like @pengwynn is already working with students on this problem. I've proposed that we remove it from the suggested projects list in https://github.com/github/gsoc/pull/25.

**Comment by shanzi** [comment]
Wow, what a pity. I have really considered a lot about it.

Thanks for notification about it.

**Comment by shanzi** [comment]
@pengwynn @bkeepers 

Though the idea has been removed, I'd still like to provide my latest idea for this idea in case it will be helpful.

After more consideration, I think hyper json schema may need too much work for `octokit-go`, but code generation is still a good solution. In fact, I think it is the only right way as Go 1.4 has just provided a new cli command: `go generate`.

I have read some related articles about `go generate`, one of the most helpful is [this article](http://blog.golang.org/generate) from golang's official blog.

So the final solution is simple now, instead of expanding URL every step traveling through the APIs, just write a script to generate the corresponding method for each resource and run `go generate`. Then we can use these methods to switch to another resource directly just like that in `octokit.rb`.

I guess someone must have already had the same idea ahead of me. But if not so, this idea should be helpful :)

**Comment by pengwynn** [comment]
Thanks for the input @shanzi. I think JSON schema holds a lot of promise and I love what Heroku has done with it for their APIs. The Platform team hopes to provide those for our APIs one day.

I'm hopeful we can create a truly hypermedia-driven API client in Go without them though. Feel free to continue the discussion in that repository if you'd like to join in even though we're not going to do it as part of GSOC.

**Comment by shanzi** [comment]
@pengwynn Thanks for you explanation :)

Might I provide a more clear description about my latest thought here? I seems not explained it clear enough.

After more consideration I has already been convinced that a JSON schema needs too much work and it may not the best choice. But `go generate` seems still a good candidate. We need not to generate code from JSON schema, but instead from go code themselves just like the example given in the [official blog](http://blog.golang.org/generate).

For example, in the [API Discoverability](https://github.com/octokit/go-octokit#api-discoverability) section of go-octokit's documation, we get a user by:

``` go
user, _ := client.Users(userURL).One()
```

Assuming we want to get one repo of this user, current solution is:

``` go
repoURL, _ = user.ReposURL.expand(octokit.M{"repo": "test"})
repo, _ = client.Repositories(repoURL).One()
```

But an `octokit.rb` like solution might be:

``` go
user.Repos(octokit.M{"repo": "test"}).One()
```

To achieve this style, we my need yet another method on the `User` structure like:

``` go

func (user *User) repos(m octokit.M) (repos *RepositoriesService) {
    c := octokit.NewClient(nil)
    mm := octokit.M{"repo": m["repo"], "owner": user.Name}
    url, _ := user.ReposURL.expand(mm)
    repos = &RepositoriesService{client: c, URL: url}
}
```

And we may also have many other functions for `Issues`, `Starred`, `Gists` and so on. But it's not difficult to find that all of these functions are very similar and if it is in ruby, writing a `method_missing` method is enough for all these resource classes.

Here is where `go generate` should take in charge. It is like a `method_missing` for go. We just write a script in go to inspect the existing file contains the resource class such as `user.go` and `repositories.go` and register all these resources. Then we analyze all the HyperLink of a class and try to find all resource A to B transitions just like that of `User` to `Repo` and generated a go source code file contains all these functions. 

That's done, the protocol now will become more clean and it's easier to make this library more general.
I think `go generate` is just the Golang societies' solution of _meta programing_. 

I'm not sure if I am the first to come up with this idea. But it seems to me that it is a quite acceptable and elegant solution. I hope this solution will help :)
