### ISSUE TITLE
Resources for tokenizing strategies and languages learning

### ISSUE THREAD

**Issue by tarebyte** [github/gsoc#17]
Hello All,

I'm really interested working on the [tokenization of grammar bundles](https://github.com/github/gsoc#use-grammar-bundles-to-tokenize-languages) for linguist.

Does anyone have any good resources for learning more about language learning and tokenizing strategies? I would like to be able to try and make a more concrete plan in my proposal.

Thanks!

**Comment by johndbritton** [comment]
@bkeepers and @arfon might have some ideas.

**Comment by johndbritton** [comment]
Also I think @aroben knows a thing or two about tokenization strategies. Any suggestions for further reading?

**Comment by aroben** [comment]
Hi @tarebyte, sorry for taking so long to reply.

I don't really know anything about language learning, and in fact I actually know very little about Linguist's current tokenization/classification code. But I do know about the "grammar bundles" that are mentioned in the GSOC project description, so I can tell you a little more about them.

Each bundle (which is really just a repository that we include as a submodule) contains one or more [TextMate-style language grammars](http://manual.macromates.com/en/language_grammars). The grammars are either in XML, CSON, or JSON, but they all have they same structure. [Here's an example](https://github.com/textmate/ruby.tmbundle/blob/880adadd728c6e3ffa452b7130a1fdc7767b2808/Syntaxes/Ruby.plist). They essentially define a set of regular expressions to be used to parse a source file of a particular language. When the regular expression is matched, the matched string is assigned a "scope" with a name like `entity.name.type.module.ruby`. We use these grammars for syntax highlighting on github.com. We essentially have a mapping from scope names to CSS rules. So, for example, all `entity.name.type.module.ruby` strings could get colored red.

I believe the idea in the project proposal is to use these grammars to replace [Linguist's tokenizer](https://github.com/github/linguist/blob/53c3cb382c64766ab984e84ca41d90a890b285ed/lib/linguist/tokenizer.rb). One thing I'm not clear on is that the tokenizer is used to determine what language a file is in, but the language grammars require you to already know what language the file is in. It feels like a chicken-and-egg problem to me. But maybe I'm misunderstanding the proposal. @bkeepers and @arfon should be able to clear this up!

**Comment by bkeepers** [comment]
Sorry I missed this last week.

> One thing I'm not clear on is that the tokenizer is used to determine what language a file is in, but the language grammars require you to already know what language the file is in. It feels like a chicken-and-egg problem to me. But maybe I'm misunderstanding the proposal. @bkeepers and @arfon should be able to clear this up!

By the time the [classifier gets called](https://github.com/github/linguist/blob/master/lib/linguist/classifier.rb#L18-L23), there is already a list of candidate languages (based on filename/extension). So the idea is that we would use the syntax bundles to tokenize the blob for each candidate language.

**Comment by bkeepers** [comment]
Hey @terebyte, let us know if you have any other questions.
