### ISSUE TITLE
gsoc project idea

### ISSUE THREAD

**Issue by ghost** [github/gsoc#19]
Hey ,
I just had an idea for a gsoc project and I'd like to share. The command line interface of git may seem daunting to new contributors which results in not contributing to the code world at all. What I'd like to suggest is a project (a simple one) in which we just have to create a gui for git.

Thank you,

p.s: I'd like to implement this using Tkinter python :D Or swings java

**Comment by johndbritton** [comment]
Hi @ronak9896. GSoC proposals must be for contributing to existing open source projects that we maintain. We don't maintain an open source Git GUI and we're not able to accept proposals to start new projects.
