### ISSUE TITLE
Is it possible to work on something related to Github's front-end?

### ISSUE THREAD

**Issue by BraulioVM** [github/gsoc#2]
Hi! I just saw that github was accepted into the GSoC and got excited about working on features I would really love to see on github. These are features I'd like to see on github that I feel I could work on:
- PDF preview mode (with pdf.js)
- LaTeX preview mode
- LaTeX editing mode

I know that github itself is not an open source project, but I guess it could be possible to develop an open source solution to make these features easy to integrate into github.

What do you think about these?

**Comment by johndbritton** [comment]
Hi @BraulioVM, thanks for your interest. We're only accepting proposals for existing open source projects that we are maintainers of. GitHub itself isn't an open source project. You can find a list of project ideas in the README in this repo and you can also check out some of our other open source projects here: https://github.com/github
