### ISSUE TITLE
Supporting Homebrew without XCode tools

### ISSUE THREAD

**Issue by tarebyte** [github/gsoc#20]
Getting rid of the XCode Command Line tools dependency would be really useful for the [Boxen Project](https://boxen.github.com).

Are there any other resources for learning about the command line tools other than [this one](https://developer.apple.com/library/ios/technotes/tn2339/_index.html#//apple_ref/doc/uid/DTS40014588-CH1-WHAT_IS_THE_COMMAND_LINE_TOOLS_PACKAGE_).

/cc @mikemcquaid

**Comment by MikeMcQuaid** [comment]
@tarebyte Not hugely although if you have questions or suggestions for additions I can make them. Do you have anyone in mind? In short: the main issue is `install_name_tool` being needed for bottle relocations and we'll need to either remove that requirement or ship a binary package of it (obviously not itself as a bottle).

**Comment by tarebyte** [comment]
Not right now, I'm just trying to understand the scope of the project. I'm also trying to understand all of the tooling involved.

**Comment by MikeMcQuaid** [comment]
Ok. Let me know if you have any README changes I should make otherwise: closing this out for now, thanks!

**Comment by MikeMcQuaid** [comment]
@tarebyte Was scrolling through old GSoC issues and saw this. Fun how history ends up 👋 😀
