### ISSUE TITLE
Adding features and possible creating a GUI for teachers_pet

### ISSUE THREAD

**Issue by tarebyte** [github/gsoc#21]
I've been using teachers_pet this semester for grading, and have had my co graders using it as well.

There are some features I would like to add, but I've gotten feedback that there are people would like the option of using a GUI or the CLI.

I'd like to get some thoughts on this.

/cc @johndbritton

**Comment by johndbritton** [comment]
I'd be open to a proposal for a GUI, preferably web based.

**Comment by tarebyte** [comment]
@johndbritton do you think it would be more preferable that the web base GUI runs locally, or should this be deployed as it's own application and the code be open sourced like [24 Pull Requests](https://github.com/24pullrequests/24pullrequests)?

**Comment by MikeMcQuaid** [comment]
> @johndbritton do you think it would be more preferable that the web base GUI runs locally, or should this be deployed as it's own application and the code be open sourced like 24 Pull Requests?

Something that could run on Heroku would be great.

**Comment by tarebyte** [comment]
Would we want to expand upon the teachers_pets gem or start a new project?

**Comment by tarebyte** [comment]
I wasn't sure if proposing new projects was ok.

**Comment by johndbritton** [comment]
I agree with @mikemcquaid, open source hosted web application.

> Would we want to expand upon the teachers_pets gem or start a new project?

GSoC is only for existing projects. I think you could make a case that you're expanding upon `teachers_pet` especially if you use it as a library of sorts.

**Comment by mikehelmick** [comment]
My intention when I started the project was to make it cloud hosted and open source.

There are some pretty important security implications when going with hosting that need to be fully thought out.

**Comment by tarebyte** [comment]
@mikehelmick can you give a few examples?

**Comment by bkeepers** [comment]
:metal: thanks for applying. We're working on reviews now and will be in touch. Let us know if you have any other questions.

**Comment by pchaigno** [comment]
> GSoC is only for existing projects.

@johndbritton Unless it changed since 2010, projects developed from scratch are accepted too (at least on Google side). For instance, Cuckoo sandbox (used in Virustotal) was developed during GSoC 2010.

**Comment by johndbritton** [comment]
@pchaigno I was unaware. When I participated in GSoC in 2008 I believe the rule was only existing projects which very well may have changed.

**Comment by pchaigno** [comment]
@johndbritton I just asked carols on IRC. It may have been a policy in the first years (she couldn't say) but it's now accepted, at least on Google's side ;)
