### ISSUE TITLE
idea: workshopper for atom-shell

### ISSUE THREAD

**Issue by ghost** [github/gsoc#22]
Based on the discussion in #15 on command line based tools for atom-shell, I would like to propose a project idea to build a workshopper for getting started with atom-shell development.

A [workshopper](https://github.com/rvagg/workshopper) is an interactive tutorial inside the command line based on a specific topic, that contains a tutorial followed by a problem on the topic that the player tries to solve based on what he/she learnt in that tutorial.

Workshoppers were started by the [nodeschool](http://nodeschool.io/) community, and today we have workshoppers on a wide range of topics, from the basics of [JavaScript](https://github.com/sethvincent/javascripting) and [node](https://github.com/rvagg/learnyounode), individual topics like [streams](https://github.com/substack/stream-adventure) and [promises](https://github.com/stevekane/promise-it-wont-hurt), and for learning software packages like [express](https://github.com/azat-co/expressworks), [browserify](https://github.com/substack/browserify-adventure) and [leveldb](https://github.com/rvagg/levelmeup). GitHub's own @jlord maintains the
official workshopper on [git](https://github.com/jlord/git-it).

During the summer I would like to create a workshopper for atom shell. A rough plan is to start with
installation, and finish with packaging and distribution strategies, while in the middle lessons we can focus on topics like App Menus, Task Tray support, Events(Online/Offline), kiosk mode, protocol handling etc. We can include lessons on the basics of browser and client scripts and the separation between them as well as a portion on selenium and webdriver and how developers can run automated tests for their atom-shell apps. This is obviously a rough idea for the project, just off the top of my head.

A rough schedule for the project would involve designing 1-2 lessons a week, with a tutorial and appropriate documentation, and I would also like to do a preliminary release at the time of the mid-term evaluation for the community to try it out and provide feedback.

Oh and my name is Suyash and I am an undergrad at [IIT Roorkee](http://www.iitr.ac.in)

Cheers!

**Comment by zcbenz** [comment]
Hi @suyash, this sounds a quite good idea to me! Can you create a pull request for your idea?

**Comment by jlord** [comment]
:sparkles: workshoppers :sparkles:

**Comment by ghost** [comment]
closing this for now since #29 was merged.

**Comment by varunagrawal** [comment]
Hey. I am looking to participate in GSoC 2016 and seeing Github as one of the participating organizations helped me decide where I want to spend my energy.
I took a look at the previous GSoC's ideas page and see that this one wasn't taken up. Is it still available to work on and/or are there any other ideas for me to start with?

**Comment by varunagrawal** [comment]
For that matter I can even work on developing IDE and editor plugins for developing Atom shell apps.
I have been using Atom since before it was released and I use it for everything that can't be handled by VS or Eclipse.
Hoping to hear back about this soon!
