### ISSUE TITLE
Is there any special requirements for writing proposal?

### ISSUE THREAD

**Issue by shanzi** [github/gsoc#24]
Hi dear mentors,

I'd like to know is there any special requirements for the proposal document submitted. 
For example:
1. The format of the document (plain text, docx or pdf)?
2. What information should be included about the candidates?
3. Instructions for naming the document that will be submitted?

**Comment by johndbritton** [comment]
Hi @shanzi,

We don't have a specific format, but you might want to check out this blog post for some tips: http://teom.org/blog/kde/how-to-write-a-kick-ass-proposal-for-google-summer-of-code/
