### ISSUE TITLE
Tools to begin searching for issues with Atom's parsing performance

### ISSUE THREAD

**Issue by dbenson24** [github/gsoc#26]
@kevinsawicki since this seems to be your area
Do you have any recommendations for debuggers to start stepping through the code to figure out where the issues might be?

**Comment by kevinsawicki** [comment]
The tokenizer library we currently use is [first-mate](https://github.com/atom/first-mate)

You can run the current benchmarks by:

``` bash
git clone https://github.com/atom/first-mate
cd first-mate
npm install
npm run benchmark
```

Here is where Atom starts chunking up lines to tokenized: https://github.com/atom/atom/blob/48d4ea0907e8aba68a8734484ceabdf3f0d02530/src/tokenized-buffer.coffee#L139-L144

The dev tools inside Atom is usually a great place to start profiling, looking at timelines, and checking the allocations. You can toggle it using `cmd-alt-i` on Mac. If you've never used the dev tools before you may want to read https://developer.chrome.com/devtools first.

Hope this helps.

**Comment by bkeepers** [comment]
@dbenson24 I'm going to close this, but feel free to post any follow up questions here.
