### ISSUE TITLE
how do I add a Personal Project as Proposal ?

### ISSUE THREAD

**Issue by ninjatrench** [github/gsoc#28]
Hello, I have an good project idea, which may help many developers as well as other organizations, so how do I add that as a project proposal under github ? 

Thanks

**Comment by MikeMcQuaid** [comment]
@ninjatrench It's probably worth detailing your project here and discussing it before submitting a proposal so we can give you advice. Thanks!

**Comment by ninjatrench** [comment]
@mikemcquaid 
Title : pipHorizon

I am planning to make rest API which can be used to deploy python based projects over the server, for example just like there is tomcat-admin tool to deploy war files similarly there can be one for python based projects.

for example an developer will first login, then click to create new project, select directory where to deploy, can choose if he/she wants virtualenv or not, then upload requirements.txt file to prepare python dependency, and upload zip file(that contains python files)
our program will automatically setup everything as needed, 
then user can even give entry point file, for example out of 10 files from my project.zip user can choose a particular file which will work as starting point. 
So after chosing that, he/she can directly start and stop file from restApi instead of logging again and again into ssh and doing the stuff.

Second advantage apart from easing developers work is that, in big organization where multiple projects needs to be deployed this can work as handy tool for managing projects like, start stop add dependency, updating etc. 
also org need not share ssh details with every developer instead they can create a user in this rest-api who will only be able to maintain or handle his particular projects.

(This idea is not shared with any other mentoring organization of Gsoc, or any other company )

Thanks.

**Comment by MikeMcQuaid** [comment]
@ninjatrench We're actually only accepting submissions for projects on GitHub's open source projects (and Homebrew) as mentioned in the README of this repository. Sounds like a neat idea but I think you'll struggle to do it as part of Summer of Code. Sorry!

**Comment by ninjatrench** [comment]
@mikemcquaid 
Do I hold the right of applying the above proposal to any other organization under Gsoc 15 ?

**Comment by MikeMcQuaid** [comment]
@ninjatrench I'm not sure but I don't think so. Google Summer of Code is for working on existing open-source projects rather than creating new ones.
