### ISSUE TITLE
Atom intelligent features

### ISSUE THREAD

**Issue by nkt** [github/gsoc#3]
Did you thought about Atom as an IDE? I mean Atom supports basic completion based on tokens inside file, but it's not a big deal to parse required files (in js).
Also atom natively supports js (cause it's written using it), so we could develop something like `spy-js` in webstorm. We could collect runtime information for completion improvement.

**Comment by johndbritton** [comment]
We have some project ideas for Atom in the README, but are open to other proposals as well. It'd need to be a well formed proposal that is appropriately scoped for the summer.
