### ISSUE TITLE
GSoC 2015: Applying with Atom

### ISSUE THREAD

**Issue by divyanshu013** [github/gsoc#30]
Hi, I'm interested in participating with Atom for GSoC 2015. I'm an active open source contributor and quite well versed in CoffeeScript, JavaScript, Python,  C, C++. I'm interested in the following ideas for Atom:
1. Improve Atom's parser performance
2. Implement support for non-US keyboard layouts in Atom
3. Improve text rendering in Atom

I've already set up my dev environment. @kevinsawicki could you please point me in the right direction as how to proceed and which project would be the most beneficial to the community so that I could start strengthening my proposal?

**Comment by kevinsawicki** [comment]
> which project would be the most beneficial to the community

1 would have the largest impact since it would improve the performance for every single person using Atom. But 2 and 3 are also incredibly important for making Atom universally approachable for people using any keyboard language and any character set.

**Comment by divyanshu013** [comment]
@kevinsawicki thanks for an earnest reply. I'm interested in working on 'Improving Atom's parser performance'. I've gone through atom/atom#979 and atom/atom#1667 and already set up my dev environment. Could you please help me getting started with some 'good-for-newbies' issues or does the selection depends on solving the mentioned issues? Thanks!

**Comment by divyanshu013** [comment]
Thanks @kevinsawicki! I've already set up my dev environment and doing some research on this. Could you please suggest what should be my next step?

**Comment by kevinsawicki** [comment]
> Could you please suggest what should be my next step?

For which project?

**Comment by divyanshu013** [comment]
I'm currently doing some research on 'Improve Text Rendering in Atom.'

**Comment by kevinsawicki** [comment]
> Improve Text Rendering in Atom.

Creating some failing tests would be a good place to start for investigating issues like https://github.com/atom/atom/issues/1783 and https://github.com/atom/atom/issues/4595

**Comment by divyanshu013** [comment]
Great! I'll do so. Thanks!

**Comment by kigawas** [comment]
I'd like to help fix the 'Improve text rendering in Atom' issue for GSoC 2015. 
What should I do next to apply this project, for instance, writing a application document or something else?

**Comment by MikeMcQuaid** [comment]
@babykiss4ever This should be useful: https://github.com/github/gsoc/blob/master/proposal-template.md Good luck!

**Comment by kigawas** [comment]
@mikemcquaid Thanks for your ardent advice, now I just finished uploading the proposal :）
