### ISSUE TITLE
Project on Hub under Gsoc'15

### ISSUE THREAD

**Issue by prabhanshu1** [github/gsoc#31]
Hi,
I am quite interested in the project "Create support for defining extensible shell completions" .And i want to do the project under Gsoc'15.

I am quite familiar with bash,and have used fish and zsh for more than 2-3 months, i had previously done some research about bash completion when i was trying to think of implementing fish like autosuggestion in bash.
please give me some direction to proceed for this project,and some reference material to get me started

**Comment by johndbritton** [comment]
@mislav is the mentor for Hub and might be able to provide some more details.

**Comment by prabhanshu1** [comment]
Hi @johndbritton 
what should i do now i have very less days to write the proposal and @mislav has not responded yet, its been 12 days, that i have been waiting for the response.
  Meanwhile i have been working on my shell scripting skill, and the bash completions.
can you suggest some important things before i submit the proposal.

Thanks
prabhanshu abhishek

**Comment by mislav** [comment]
Hi @prabhanshu1, sorry for the late reply. I'm going to add my thoughts to #34 right now because you both ask the same questions. Please subscribe to that issue for updates!
