### ISSUE TITLE
How do you use Linguist in practice

### ISSUE THREAD

**Issue by arapat** [github/gsoc#32]
Hi, I have roughly viewed the code base of linguist project. Before starting to play with the code, I would like to ask several questions.
1. How is the performance of Linguist in production? If someone starts work on this project, will he/she has access to the records of GitHub users reporting misdetection on their source files?
2. How are the sample data selected? This is quite critical to the training models of bayesian learning.
3. One of the project ideas for Linguist project is to aggregate the predictions from multiple predictors. However, I didn't really see how you current aggregation strategy is from your code base, i.e. how do you detect the programming language using the multiple classifier at this moment? Sorry if I missed something.
4. Have you ever thought about using classification algorithms other than bayesian classifier? According to the paper in reference, bayesian classifier looks like a very good fit for this problem. However, I still wonder how other classification algorithms works on programming language classification problem.

One intuitive attempt to the second project idea is to apply several different classifiers, then we can maybe use some boosting techniques to aggregate them. However, the deterministic detection strategies (by looking at file name extension, shebang, etc) should be very powerful (predict correctly almost every time), and will take much larger weights comparing to the probabilistic classifiers. I am very curious how it will actually work on real dataset.

Thanks!

**Comment by johndbritton** [comment]
@github/linguist should be able to answer some of these questions.

**Comment by bkeepers** [comment]
Hi @arapat

Check out https://github.com/github/linguist/issues/2195 for more information.

> How is the performance of Linguist in production?

It's ok. One of the biggest issues right now is the memory usage of the classifier.

> If someone starts work on this project, will he/she has access to the records of GitHub users reporting misdetection on their source files?

When people report issues with classification, we typically ask them if the can point us to a public project that shows the issue.

> How are the sample data selected? This is quite critical to the training models of bayesian learning.

Right now, we have [some samples](https://github.com/github/linguist/tree/master/samples) that have been manually curated. We need a lot more.

> One of the project ideas for Linguist project is to aggregate the predictions from multiple predictors. However, I didn't really see how you current aggregation strategy is from your code base, i.e. how do you detect the programming language using the multiple classifier at this moment? Sorry if I missed something.

We currently use multiple [strategies](https://github.com/github/linguist/blob/1a3680bba6f4676087b1a883a62cb16d29408bfb/lib/linguist/language.rb#L90-L96) to detect the language. We return as soon as a strategy returns exactly one result.

> Have you ever thought about using classification algorithms other than bayesian classifier? According to the paper in reference, bayesian classifier looks like a very good fit for this problem. However, I still wonder how other classification algorithms works on programming language classification problem.

We're definitely open to other ideas, but we haven't explored any ourselves.

**Comment by arapat** [comment]
@bkeepers Awesome! Thanks for explaining!
