### ISSUE TITLE
Implement support for non-US keyboard layouts in Atom

### ISSUE THREAD

**Issue by PavelDemyanenko** [github/gsoc#33]
Hi guys,

I find this issue interesting for me cause I'm not in latin group too and it skills required are quite close to me.

Cheers,
Pavel

**Comment by johndbritton** [comment]
@PavelDemyanenko You should do some more investigation into the project and ask any questions you have about it. If you're interested you'll need to apply through the GSoC website once student applications open. Now is a great time to start doing some research.

**Comment by PavelDemyanenko** [comment]
@johndbritton thanks for clarification, I'll try!
