### ISSUE TITLE
Completion Scripts for Hub

### ISSUE THREAD

**Issue by hasit** [github/gsoc#34]
Hello. I am Hasit Mistry and I am doing my MS in Computer Science and Software Engineering from University of Washington Bothell.

I have been using fish for over a year now and I was a zsh user before that. I have been tinkering with the autocompletion of hub for some days and I have noticed the following:
1. fish autocomplete script file is missing. Is that something that I can start working on? A little help would be great.
2. I recently learnt that fish can generate completion scripts using man pages. I posted a comment on hub repo issue [#656](https://github.com/github/hub/issues/656) asking for help and providing a suggestion.

I am interested in implementing a way to define these shell completions for bash, zsh and fish. While fish does this [automatically from man pages](http://fishshell.com/assets/img/screenshots/man_completions.png), hub expects an alias to git and due to this reason, there are no options in the hub man pages for fish to generate an autocompletion script from. I confirmed that by looking into the `~/.config/fish/generated_completions/` folder.

A possible way of doing this:
Define all the completion options in a text format (JSON/XML maybe?) and make a Go program to read this file and generate autocomplete scripts for each shell. A Go script along the lines of `fish_update_completions` script.

I see @mislav is in charge of mentoring Hub as suggested by @johndbritton. I am very excited about taking up this task and any help or pointers in the right direction would be of great help.
Thank you.

**Comment by mislav** [comment]
Hi @hasit sorry for the late reply. To address your questions:
1. Yes, we miss fish autocompletion script. This is under the scope of the GSoC project's deliverables, so if this project gets accepted, then a student will work on this.
2. I didn't know that; if we could pull it off (write man pages so they can be parsed by fish) that would be one good way of approaching the problem.

> A possible ways of doing this:
> Define all the completion options in a text format (JSON/XML maybe?) and make a Go program to read this file and generate autocomplete scripts for each shell.

Something like that I had in mind, but I think JSON or XML would be poor formats for authoring by hand in a text file. A better format would be some line-based markup format that we invent ourselves, or we could adopt the fish man-parsing strategy and implement the same in bash and zsh. Then, we could generate all completion scripts from documentation.

**Comment by hasit** [comment]
@mislav no problem, I guess you must have been busy. In the meanwhile, I have been reading more about fish and how it performs autocompletion.
1. Would this differ from the idea of creating a common way of making completion scripts? Or is it a subset of the main project (since the end product would be to make this automatically)? I feel, working on this would give me a better understanding of the way fish handles autocompletion and this knowledge can be then applied to the project overall. I am planning to include this in the later stages of the Ideation Phase and early stages of the Development Phase of the project in my proposal.
2. I completely agree. Once we have that ready, we could look at [how fish reads the man-pages](https://github.com/fish-shell/fish-shell/blob/master/share/tools/create_manpage_completions.py) and generates scripts. Documentation on [writing your own completion scripts](http://fishshell.com/docs/current/index.html#completion) is pretty well written in my opinion and I believe is a very good starting point.

> Something like that I had in mind, but I think JSON or XML would be poor formats for authoring by hand in a text file. A better format would be some line-based markup format that we invent ourselves

Not necessarily. I mentioned JSON and XML because I am aware of their syntax (having used them in various projects in the past). Writing the commands in JSON or XML specific format would be, in my mind at least, an alternative to rewriting and reorganizing the whole of man-pages. A format I had in mind goes something like this:

```
hub //being the root node - level 0
|_ command 1 //various commands - level 1
    |_ option(s) //other options placed lower in the tree - level 2 onwards?
|_ command 2
    |_ option(s)
```

But then again, I am completely open to discussions about making our own line-based markup format specifically for this purpose. What do you think?

This project is something I would enjoy working on. I will be submitting a more detailed proposal in a day or two. Are there any specific things you would like to me to include in the proposal related to this project apart from the ones mentioned in [proposal-template.md](https://github.com/github/gsoc/blob/master/proposal-template.md))?
Also, do you think it is a good idea to get my proposal checked by you personally before I submit through the GSoC page? That would be great help in strengthening the proposal.

**Comment by mislav** [comment]
> But then again, I am completely open to discussions about making our own line-based markup format specifically for this purpose. What do you think?

I think the specifics of the format don't have to be decided up front. This is something that we can come up going back-and-forth during development. I _am_ strongly opposed to XML, but in the end, defining this detail is another part of the project :)

> do you think it is a good idea to get my proposal checked by you personally before I submit through the GSoC page?

No, let's keep it trough Melange. We are supposed to help you revise your proposal through that platform anyway. :+1:

**Comment by hasit** [comment]
@mislav Thank you for all the help. I'll get on to finishing my proposal. Looking forward to your comments on it.

**Comment by mislav** [comment]
Some extra things that you and anyone reading this should consider when creating a roadmap for this project:
1. If we end up generating completions from man pages, then a part of this project will be to improve our existing man page, beginning by splitting it into separate pages, as well as consolidating that with the inline help text that is embedded in Go source for each command.
2. Hub completions wrap completion results for git's own commands. Some hub commands add extra parameters to git core commands. This fact makes our completion scripts potentially more complex to set up than regular completion scripts (for commands that don't wrap anything).
3. Part of this project is to make shell completion robust across platforms. We had some problem with different users having different zsh options enabled in their environment, and that in turn breaking hub shell completion. For each shell, I think it would be a good idea to think about creating some methods that we could use internally to debug why a completion script didn't return the results that we expected, or didn't return anything at all.
4. I'm going to encourage everyone to create automated tests for shell completions. [We have rudimentary automated tests](https://github.com/github/hub/blob/e359d0918580acedcc7c6fe9f15e46c570582537/features/zsh_completion.feature) right now for bash and zsh, and I'd like those to be expanded with new functionality and fish support. The tests work by spin up a shell in a subprocess within tmux, sending keystrokes to it (such as <kbd>Tab</kbd>), and inspecting the printed result.

**Comment by hasit** [comment]
@mislav I have submitted my proposal. Thank you for all the help. I look forward to reading your comments and suggestions on it.

**Comment by prabhanshu1** [comment]
@mislav  I have also submitted my proposal. Please give your valuable suggestion on it.

**Comment by bkeepers** [comment]
Thanks for your proposals! We are working on reviewing them and will let you know if we have any questions or concerns.
