### ISSUE TITLE
Atom Project Questions

### ISSUE THREAD

**Issue by randomPoison** [github/gsoc#35]
Hi,

I'm interested in the GSoC projects with Atom, especially the one relating to improving the performance of the parser. I was wondering if @kevinsawicki had any advice about where to start. I'm experienced with C++ and I've worked with javascript in a couple of projects, but I haven't done any work with the atom source. I'm getting the build environment set up, and I've been looking at atom/atom#979 which looks like it would be a good starting point. I'm also hoping it will be a bit easier.

I appreciate any help you can offer. Thanks.

**Comment by randomPoison** [comment]
I've got some ideas for a more concrete proposal, so I'm going to open a different one to get more specific feedback.

**Comment by bkeepers** [comment]
@excaliburHisSheath looking forward to seeing your proposal. Feel free to create an issue here to discuss it or ask for feedback!
