### ISSUE TITLE
GSOC idea: atom autocompletion.

### ISSUE THREAD

**Issue by nkt** [github/gsoc#37]
I suggest to add in atom autocompletion for JS based on static analysis. Now atom-completion collect parsed identifiers:
<img src="https://cloud.githubusercontent.com/assets/3505878/6548005/8b378704-c5fb-11e4-91b2-ec8e2248817b.png" width="300">
But there are already exists tools (like babel) with great api for retrieving js ast.
So we just need to write tool that gives more brains to completion mechanism.

Maybe, if it's possible do during summer - parse dependencies and add correct completion for them too.

**Comment by benogle** [comment]
This is interesting. Have you tried https://github.com/tststs/atom-ternjs?

**Comment by nkt** [comment]
@benogle yep, I've tried. This project works based on plugins. For example there are angular, node, require.js, jquery plugins. But I'm suggest to analyse code and create autocompletion based on it.
Actually previously I were using WebStorm by JetBrains. But there is a huge problem - ide index all code and suggest completion looks like every code in global namespace. As you know, today every js file is the module with its individual scope.

**Comment by nkt** [comment]
That's how atom-ternjs works now.
<img src="https://cloud.githubusercontent.com/assets/3505878/6731381/af4d579c-ce55-11e4-8e5b-793247b9d1b9.png" width=300>
Ternjs written by `acorn` author, so it's could support es6.

**Comment by despairblue** [comment]
@nkt though it does not yet completely, right? I had to disable it since it kept throwing errors if the file contained arrow function.

**Comment by nkt** [comment]
@despairblue I've not found [your commits](https://github.com/tststs/atom-ternjs/commits?author=despairblue) that disable something.
Also I've tried to use sublime `ternjs` plugin and this simple completion also doesn't working fine.

**Comment by despairblue** [comment]
@nkt sorry, you misunderstood me, I had to disable the atom-ternjs in atom, since it kept piling up errors on the right hand side. And those weren't atom-ternjs errors, but ternjs errors. I'll just enable it and post a screenshot of it when it happens again. I meant to report them to ternjs anyway.

**Comment by despairblue** [comment]
@nkt that's what I meant: https://github.com/marijnh/tern/issues/510 it's generator functions not arrow functions that don't work.

Sorry for getting off topic :/
Stopping now.

**Comment by nkt** [comment]
I also want to participate in GSOC with Atom team. I'm on 3rd course in Russian university MIREA on "Applied Mathematics". I pretty know js, coffee, but prefer es6, also I know C++, but didn't wrote something significant using it. I'm just started work on coursework - HTTP 1.0 server, it's will be written using C++ and C.
If my idea will not be accepted, I'm ready work on "Improve Atom's parser performance" or "IDE and editor integrations to develop Atom Shell apps".
I've been working on [Zephir language](https://github.com/phalcon/zephir) and have written [IDEA plugin](https://github.com/zephir-lang/idea-plugin) for this language.
@bkeepers, what I have to do right now?

**Comment by MikeMcQuaid** [comment]
@nkt Just submit a proposal based on [the template](https://github.com/github/gsoc/blob/master/proposal-template.md) and we'll review it.

**Comment by bkeepers** [comment]
The application deadline is passed, so I'm going to close this. Let us know if you have any other questions.

**Comment by nkt** [comment]
@bkeepers 

> If my idea will not be accepted, I'm ready work on "Improve Atom's parser performance" or "IDE and editor integrations to develop Atom Shell apps".

Did you accept my application for participation?

**Comment by bkeepers** [comment]
We're still reviewing proposals. We'll be in touch soon.

**Comment by nkt** [comment]
@bkeepers thanks, I'll be waiting.
