### ISSUE TITLE
Atom Project Proposal: Implement Segmented Lines

### ISSUE THREAD

**Issue by randomPoison** [github/gsoc#39]
I've been going over the discussion in atom/atom#979 and looking at what's causing the performance problems when it comes to long lines. On the surface the problem is that Atom treats lines a single strings, which means that a long line can be subjected to multiple O(n^2) regex searches in the process of parsing it, which takes huge amounts of time and results in hangs. @maxbrunsfeld has suggested replacing the regex searches with a single linear time scanner, and @prasoon2211 has suggested replacing the existing regex library with one that performs in linear time. While these would alleviate the issues with parsing times, I think there are more core issues with the way that Atom represents documents that can be fixed to yield more overall improvements.

My proposal is to further break up individual lines into smaller segments that allow editing and parsing to take place at a more manageable scale. This would allow an effective cap on how much text would need to be parsed in a single call, which allows for better scaling even with exponential regex search times. I think this solution is a good start towards a more efficient internal representation of documents for Atom. It should be fairly easy to implement in CoffeeScript without having to drop to native code, and even if it fails to yield a significant performance increase it should be fairly illuminating as to where other improvements can be made.

As for GSoC, I'm guessing this alone will not be sufficient to fill the work period, so I think the next step would be to re-implement the most performance-heavy parts of the internal text buffer in C++. This would allow directly interfacing with the regex parser without the need to handle strings in javascript, and would reduce the burden on the garbage collector since string processing tends to be pretty rough on the GC (though perhaps this is not as much of an issue with Atom).

I'm open to all thoughts and feedback. Thanks!

/cc @kevinsawicki @bkeepers

**Comment by johndbritton** [comment]
I'm not an expert in Atom, but this sounds like you've got a pretty good handle on your proposal. If you've got specific questions, definitely post them here.

**Comment by randomPoison** [comment]
Thanks! I haven't had a chance to start drafting up a full proposal, I've been pretty busy with finals at school, but if I need any help I'll be sure to ask.

**Comment by kevinsawicki** [comment]
Really interesting writeup, a proposal for this would be great, thanks!
