### ISSUE TITLE
use TypeScript .d.ts type definitions to as javascript library interface document (and provides completion)

### ISSUE THREAD

**Issue by EasyHard** [github/gsoc#40]
Problem:
A big pain point of developing with a dynamic language is that you need to look into libraries' document to figure out their interfaces and how these interfaces should be used. Even you are familiar with the semantic of those interfaces, you may still need to look into the document to make sure you put arguments in the right order. This is really frustrating. Static analyzing does not always get its job done due to the dynamic nature of the language.

And this problem is more painful in the javascript would because JS supports only minimum language feature and lots of things are handled in runtime by manipulating `arguments`. 

There is already some type inference engine designed to static analyzing JS code and provide completion information like https://github.com/marijnh/tern. But they could be fail to analyze complex library like https://github.com/request/request, due to the super dynamic nature of the language.

Solution:
My solution tries to address down the this problem, by introducing the type definition files of TypeScript as an external, machine understandable source of library document. 

Even though you can make extremely irregular interface in JS, programmers are all most always make their interfaces fit into some rules. That's why we could use type system to describe the interface, like what TypeScript trying to do. And the good part of type system is that it can be understood by algorithm. So we could take them as some kind of machine-readable document of the library.

And lots of pure javascript libraries have well-written type definitions in TypeScript, like this repo https://github.com/borisyankov/DefinitelyTyped/ They are created for the TypeScript guys to bring the pure javascript libraries into their type checking world. But we can also use them as documents for javascript developers. By parsing them, we can implement an awesome autocompletion system and library exploration in Atom for JS development.  

Expect Output:
A Atom extension that provide a way to give autocompletion and typing information based on TypeScript definitions for javascript development, and also provides auto-completion functionality.

If you have any idea of my proposal, please let me know. I am also open to the listed ideas, like
the parse performance problem,

**Comment by bkeepers** [comment]
Hi @EasyHard. This definitely sounds interesting. Unfortunately, I don't think this is a project that our Atom team has time to mentor given their other priorities. Maybe next year?
