### ISSUE TITLE
Gsoc15-Implementing Support for non-US keyboards

### ISSUE THREAD

**Issue by jatinsandilya** [github/gsoc#41]
Hi @kevinsawicki , I would like to show my interest in participating in GSOC-15 as a student. I am particularly interested in the suggested idea of Implementing support for non-US keyboard layouts in Atom. I have set up a local build of Atom and I am preparing my proposal for it. Could you guide me on what my next step could be? 
 #35 #37

**Comment by kevinsawicki** [comment]
> Could you guide me on what my next step could be? 
- Investigate how other native applications typically handle keybindings for different keyboard layouts to gain insight into any established patterns
- Investigate how to best handle detecting the [AltGr key](http://en.wikipedia.org/wiki/AltGr_key) and how to best support differentiating between its use in entering text and its use in a configured keybinding

**Comment by bkeepers** [comment]
Hi @jats22, let us know if you have any other questions.

**Comment by jatinsandilya** [comment]
Thanks for your reply @kevinsawicki and @bkeepers  . I looked into the issues 35 and 37 and although I understood the problem and the workarounds presented by the community like this one https://github.com/andischerer/atom-keyboard-localization .How effective is that? 
A simple(or naive) solution could be to add an option of various keyboard layouts to be selected by the user and map it accordingly with the workarounds there are for each specific layout but I'm sure you would have thought about this.
And as it was being presented AltGR key translates as Alt+Ctrl,well is it really a Windows only issue?

**Comment by jatinsandilya** [comment]
Also as #57 proposed can I have some tips on my proposal specifically in regard with the feature I'm proposing to implement?

**Comment by kevinsawicki** [comment]
> How effective is that? 

To be honest, I've not used that package before so I'd be interested to hear your thoughts on how it addresses the problems

>  with the workarounds there are for each specific layout

We already do some workarounds for specific problems with the dvorak layout, https://github.com/atom/atom-keymap/pull/51

So adding other workarounds might be the right solution if they behave intuitively for people using these keyboard layout.

> And as it was being presented AltGR key translates as Alt+Ctrl,well is it really a Windows only issue?

It is not a Windows only issue, people might be using a keyboard with an `AltGR` key on either Mac, Windows, or Linux, so it should be supported on all three.
