### ISSUE TITLE
Proper understanding of Linguist ideas

### ISSUE THREAD

**Issue by devtrace404** [github/gsoc#44]
As I was reading the idea list of Linguist I was not sure whether I am interpreting the exact meaning of both the ideas. This is what I interpreted of both the ideas.
--- Use grammar bundles to tokenize languages ---

In this we want to first detect the language and then highlight the syntax of the corresponding code .

--- Weighted scoring for detection strategies ----

In this we want to improve the existing code of language detection.

It would we very thankful of you if you could please correct me if I am wrong in understanding these ideas.

Thank You

**Comment by arfon** [comment]
Hi @pawandeep2155, please take a look at [this thread](https://github.com/github/linguist/issues/2195) as it should give some additional background.

**Comment by bkeepers** [comment]
@pawandeep2155 let us know if you have any other questions.
