### ISSUE TITLE
GSoC idea: Implement scripts to generate source tarball of Atom and its sibling projects.

### ISSUE THREAD

**Issue by sarveshgpt1991** [github/gsoc#45]
Hello, I was looking around for a project in Github and find the project "Implement scripts to generate source tarball of Atom and its sibling projects" very interesting. Also most of the Skills require matches to my skill sets. I've also participate in last year's GSoC.
I just want to clarify one thing. By now what we have a .deb for Atom which is compiled binary source. Now what we require is the source tarball for Atom so that ultimately will help us creating our own PPA for Atom.
I've been researching around for the way to proceed this problem, but it will be good if I can get some starters with the problem.

One more idea which I was thinking can be to implemented Atom is to introduce Chef based Cookbook.
It will be an enhancement for developers who are trying to make contribution by introducing vagrant environment for development process.
The benefit of this would be that developers can create their development environments from the same configuration, so whether working on Linux, Mac OS X, or Windows, all of them can run code in the same environment, against the same dependencies. Vagrant provides a disposable environment and consistent workflow for developing and testing. One can quickly test things like shell scripts. Vagrant also automatically set everything up that is required for that app in order to focus on doing what you do.
The other thing that needs to handle in parallel to vagrant setup is provisioning. Provisioning in Vagrant allows to automatically install software, alter configuration and manage things. The provisioning method which can be implemented is Chef. Chef operates using cookbooks, i.e. self-contained scenarios such as “installing and configuring required dependencies”. Environments are assigned cookbooks and Chef makes sure that everything is available and up to date, thus providing us the automation and re-usability part of the recipe.
This is the part where I'm experienced working last summer at GSoC.

Please let me know is this implementation worth it or not.
Thank you.

**Comment by sarveshgpt1991** [comment]
@zcbenz , please can I get any comment on this so that I can prepare my proposal.

Thank you.

**Comment by bkeepers** [comment]
Thanks for getting in touch! I think @kevinsawicki can help you out.

**Comment by sarveshgpt1991** [comment]
@kevinsawicki , please can you look through this issue.
Thank you.

**Comment by zcbenz** [comment]
Hi @sarvesh-onlyme, sorry for the late reply.

Atom itself can be built on most Linux distributions without problem, but it downloads prebuilt binaries of libchromiumcontent and atom-shell instead of building them, which makes Atom not able to run on all Linux distributions. The solution is to also build libchromiumcontent and atom-shell when building Atom, and make use of PPA and OBS to build Atom on most Linux distributions.

The challenge, is to generate source tarball for libchromiumcontent and atom-shell, and make them build without internet (which are required by PPA and OBS).

To get started, you can first get yourself familiar with libchromiumcontent.

Vagrant sounds good, but it is not suitable for heavy GUI programs like Atom.

**Comment by sarvesh-onlyme** [comment]
@zcbenz, are there any documentations for libchromiumcontent. And second thing I need to build atom-shell with the help of libchromiumcontent, where can I find instructions for this.
Thanks

**Comment by sarveshgpt1991** [comment]
Hello @zcbenz 
I just want to make sure that what I understand is right, so please correct if I'm wrong.
Atom comes with the pre-compiled binaries, which we won't want because It doesn't work for every linux based system.
To compile atom, compiled binaries of atom-shell are required. And to compile atom-shell, compiled binaries of libchromiumcontent are required.
But we require require source packages of atom-shell and libchromiumcontent so that atom can be compiled at the time of installation and also its dependencies.
For this we are suppose to provide PPA(debian based) and OPENSUSE(redhat, Arch, SUSE, etc.) for atom, atom-shell and libchromiumcontent independently.

Thanks a lot.
cc @kevinsawicki , @bkeepers

**Comment by kevinsawicki** [comment]
> so please correct if I'm wrong.

Everything you said seems correct to me :+1:

**Comment by sarveshgpt1991** [comment]
Hello @zcbenz , @kevinsawicki 
Can I personally send you my proposal before submitting to google-melange, so that you could give some feedback on that.

Thank you.

**Comment by kevinsawicki** [comment]
> Can I personally send you my proposal before submitting to google-melange

It will be easier to just review it directly in google melange so please post it there.

**Comment by sarveshgpt1991** [comment]
@kevinsawicki and @zcbenz 
I've just now submitted the proposal. Please can you review it and give me feedback on which part I'm not able to explain in detail or may be didn't explain something.
Thanks a lot.

**Comment by sarveshgpt1991** [comment]
Hello,
Sorry to get back to you again, but please if you could review and comment on my proposal, it would be easy to act on feedback with just 3 days left.
Thank you.
