### ISSUE TITLE
Homebrew: Handle formula renames and deletions

### ISSUE THREAD

**Issue by vladshablinsky** [github/gsoc#46]
Hi, I'm Vlad Shablinsky. I'm studying computer science in Belarusian State University. I really like Homebrew, it’s the project that I truly want to work on. 

I have some skills in python, git and unix, but I’m not very experienced in ruby. I know it a bit, but I can’t say I know it very well. 

I submitted a pull request with some fixings that `brew audit` shows and now I want to go further. I'm interested in "Handle formula renames and deletions" project. As far as I understood the project is to provide some kind of `brew rename A B` that handles all the renamings of binaries, directories and all of this stuff is done locally. So after the renaming I have B and I don't have A and I still have to be able to `brew upgrade B` like if it was A. Do I understand the task correctly?

**Comment by MikeMcQuaid** [comment]
Hi @vladshablinsky! It's ok to learn Ruby as you go. I commented on your PR and updating it to use `brew audit --strict` would be a good next step.

The renaming project is actually about if e.g. we wanted to rename the `wget.rb` project to `wget-new.rb` and it would need to handle e.g. migrating `Cellar/wget` to `Cellar/wget-new` and similar things on upgrade automatically rather than running a separate `brew rename` command. Let me know if that answer your question!

**Comment by vladshablinsky** [comment]
So you rename the project

**Comment by vladshablinsky** [comment]
@mikemcquaid So the name of a formula is changed not locally firstly and then I can upgrade it. For example before upgrade I have `wget.rb` and if I run `brew upgrade wget` it handles all the renames and after that I don't have `wget.rb` anymore. Instead of that I have `wget-new.rb` and all the files migrate automatically to new directories.

**Comment by MikeMcQuaid** [comment]
Yup, something like that. The new `wget-new.rb` will need metadata to tell it it used to be called `wget.rb` and how to do the upgrade/migration.

**Comment by vladshablinsky** [comment]
@mikemcquaid I got it! Could you tell me what should I start with to get into this project?

**Comment by MikeMcQuaid** [comment]
@vladshablinsky I'd just work on a proposal document at the moment and consider submitting more Homebrew PRs.

**Comment by vladshablinsky** [comment]
@mikemcquaid Thanks! Homebrew doesn't have proposal templates, does it? Are there any special "absolutely-must" things you're looking for or "no-no" things I should be aware of?

**Comment by MikeMcQuaid** [comment]
> @mikemcquaid Thanks! Homebrew doesn't have proposal templates, does it? Are there any special "absolutely-must" things you're looking for or "no-no" things I should be aware of?

We don't have templates. "Absolutely must" would be fixing the basic case where currently we can't rename formulae. "No-no" would be I guess doing some sort of drastic refactoring of all Homebrew's code rather than doing it bit-by-bit. Feel free to ask any more questions you may have when doing the proposal, though!

**Comment by vladshablinsky** [comment]
Thanks a lot @mikemcquaid! Could I show you a draft to amend something when it's ready?

**Comment by MikeMcQuaid** [comment]
@vladshablinsky Sure, happy to take a look at mike@mikemcquaid.com.

**Comment by MikeMcQuaid** [comment]
Closing this out as I assume I've answered your questions. Feel free to ask more if I haven't!

**Comment by vladshablinsky** [comment]
@mikemcquaid, I've got a question. I've been trying to solve problem with renames recently but now I'm not sure I understood everything correctly. I want to clarify what should we do if `wget.rb` migrates to `newwget.rb` and a brand new `wget.rb` appears. What should be done on `brew upgare wget`? 
Should the old `wget` be moved to `newwget` locally and then be upgraded or we just upgrade `wget` and that's it?

**Comment by MikeMcQuaid** [comment]
@vladshablinsky I think the behaviour in that edge-case could be up for debate. I'd be up for either just blacklisting the old name so we can't create new formulae with it or somehow tracking intelligently and doing the move.

**Comment by vladshablinsky** [comment]
@mikemcquaid I've been thinking about implementing the second approach, but It's tricky and haven't come up with idea yet, so I decided to ask you maybe I'm moving in the wrong direction. 
Both of the approaches have its pros and cons, I think. The second approach is difficult for understanding from the side of user, because there can be a lot of renames and a lot of formulae with the same names in different periods of time. Renamings may form cycles and other things like that. The first approach is easy to understand to user and much easier to implement than the second one.

**Comment by MikeMcQuaid** [comment]
That you are thinking about these edge cases is really great. I wouldn't worry about it too much now; I'd be OK with the proposal just stating this is something we'd need to discuss and think through a solution together.

**Comment by vladshablinsky** [comment]
Thanks, @mikemcquaid! I couldn't move on without having a particular algorithm of the second approach done and I thought it was the only possible approach that can be accepted. But since the particular implementation can be discussed later I can move on.
