### ISSUE TITLE
JS Project for GSoC

### ISSUE THREAD

**Issue by yvtheja** [github/gsoc#47]
Hi @kevinsawicki , 

I am Vishnu Teja doing my B.Tech from a deemed University National Institute of Technology, Surat, India. I am would like to do a project in Github through GSoC 2015. My skills are JS, HTML, CSS, Unit testing and Integration tests. I have been contributing Mozilla's product Firefox OS {JS, HTML,CSS} for a long time. I would like to do projects based on JS which are mentioned in idea's list which are based on Atom. Please help me with some pointers from where I can start fixing some bugs in code base to get myself fluent to codebase. I tried pinging you on IRC at #github And also please help me where I can ping you on IRC.

Thank you :)

**Comment by kevinsawicki** [comment]
> Please help me with some pointers from where I can start fixing some bugs in code base to get myself fluent to codebase.

You might want to start by looking at the issues labelled "help wanted": https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3Aatom+is%3Apublic+label%3A%22help+wanted%22

If you are looking to fix a core Atom issue, check out the bugs on the atom/atom repo:  https://github.com/atom/atom/labels/bug

> And also please help me where I can ping you on IRC.

I'm not on IRC, sorry.
