### ISSUE TITLE
Homebrew: Application packages should include all their dependencies

### ISSUE THREAD

**Issue by liudangyi** [github/gsoc#49]
Hello. I'm a college student from China and very interested in contributing for homebrew in GSoC.

However, I haven't got the meaning why we need to package all the dependencies in one directory? An important reason why we use a package manager rather than manually compile software is that it can deal with dependency automatically. It won't trouble users if `mysql` and its dependency `openssl` are all bottled.

**Comment by MikeMcQuaid** [comment]
Hi @liudangyi! The best start if you'd like to contribute to Homebrew for GSoC would be to start making a few simple PRs to e.g. submit version updates, fix `brew audit`, `brew audit --strict` warnings and adding `test do` blocks to formulae missing them.

The reason for trying to package all dependencies in a single directory is so if users e.g. upgrade `openssl` and remove the old version it won't break their `mysql` install. Additionally, to allow installation of the binary `mysql` package be a single file to download which contains all dependencies.

Feel free to ask if you have any more questions, thanks!

**Comment by liudangyi** [comment]
However, most software won't be broken if you upgrade their dynamic library dependencies because they use a naming convention to choose which version of API they use. For example, `openssl` 1.0.2 still uses `libssl.1.0.0.dylib` as its shared library filename. According to Linux convention, a library should link its `libfoo.1.0.1.so` as `libfoo.1.0.so` and `libfoo.1.so`. Thus software depending on libfoo can choose to use any of them.

**Comment by MikeMcQuaid** [comment]
Sure, it requires manually additions of `revision` tags for us though which is a pain.

**Comment by liudangyi** [comment]
Sorry, I don't follow. Why do we need to add a revision tag after a dependency is upgraded?

**Comment by MikeMcQuaid** [comment]
If they upgrade from e.g. `libssl.1.0.0.dylib` to `libssl.2.0.0.dylib` (or even sometimes minor or patch versions) sometimes they are not ABI compatible so the `revision` tag must be added to dependents so that they can be recompiled against the new version.

**Comment by liudangyi** [comment]
I see. But in that case, most dependents will need to be upgraded due to a different API.

**Comment by MikeMcQuaid** [comment]
We end up having to bump due to ABI changes more than we need to bump dependents due to API changes.

**Comment by liudangyi** [comment]
Sorry, I just mistook API for ABI... What I mean is exactly ABI, which uses a shared library mechanism. 

Say, if ABI doesn't change during an upgrade, then nothing bad will happen and dependents will work as usual. But if ABI changes, in most case we need a new version of dependents rather than a `revision`. So why do we need an all-in-one package?

**Comment by MikeMcQuaid** [comment]
We don't technically need one, I just think it would be a more elegant solution to the problem, long-term, that will be less error-prone and faster for users.

**Comment by MikeMcQuaid** [comment]
Closing this out as I assume I've answered your questions. Feel free to ask more if I haven't!
