### ISSUE TITLE
[GSoC '15] Improve Printing Support of Atom Shell

### ISSUE THREAD

**Issue by genuinelucifer** [github/gsoc#51]
I have approximately 7 years of experience in using C++ language and many of the libraries made for it. I have also developed softwares & games using Win32 API, Qt 4, SDL, OpenGL all for my own learning purpose. Currently, i am a 2nd year B.Tech student at IIT Indore,India.
For GSoC, I am interested in the project -
Improve printing support of Atom Shell.
.
Any suggestions in this regard would be helpful!
.
Regards,
Abhinav

**Comment by bwin** [comment]
I would love to see printing support for windows. Happy to see it's included in the GitHub GSoC list.
Thanks for considering this, Abhinav.
cc @zcbenz

**Comment by genuinelucifer** [comment]
I am new to Atom Shell. It would be great if you could help me get started on where to start looking (Which section of the atom shell code) for windows specific additions...

**Comment by zcbenz** [comment]
@genuinelucifer The printing related code comes from Chromium, so to get started with Atom Shell you should first get more familiar with Chromium's architecture: http://dev.chromium.org/Home.
