### ISSUE TITLE
Improve text rendering in Atom: GSOC -15 Project

### ISSUE THREAD

**Issue by kumarrishav** [github/gsoc#52]
Hi @kevinsawicki 
I want to work on this project under github umbrella. I am already done with building environment and currently i am contributing to atom packages and have already submitted patches .Also i got aware of key bindings and other important things require for working on packages and themes.
I need your guidance to work on this project, so that i can prepare a feasible and good proposal for it. I successfully completed GSOC -14 under mozilla organisation last year. My work is mostly on HTML,  css, javascript,  node,  unit testing (spec) using jasmine, mocha  frameworks and coffeescript.
Thanks

**Comment by kevinsawicki** [comment]
> I am already done with building environment and currently i am contributing to atom packages and have already submitted patches 

Awesome, great to hear :+1: 

> I need your guidance to work on this project, so that i can prepare a feasible and good proposal for it.

Okay, what can I help you with?

**Comment by kumarrishav** [comment]
@kevinsawicki Thanks for your reply.
Before writing proposal, i want to get involve with this project (Improve text rendering in Atom) and get my hands dirty with codes so that i can get clear picture of  upcoming work. From where should i get involved in it. Also do i need to have knowledge of different languages (like chinese , Japanese, Korean etc) to work on it.

**Comment by kevinsawicki** [comment]
> From where should i get involved in it.

Write test cases that fail for some of the problems mentioned in those linked issues is a great place to start.

> Also do i need to have knowledge of different languages (like chinese , Japanese, Korean etc) to work on it.

Nope, we can just work together with people that know these languages to make sure the issues are fixed and to help test out any solutions.

**Comment by kumarrishav** [comment]
@kevinsawicki  write test case that fail... <= you mean write specs (or unit test) or find the possible situations/cases (not in coding term) where those issue occurs

**Comment by kevinsawicki** [comment]
> you mean write specs (or unit test) or find the possible situations/cases (not in coding term) where those issue occurs

Either is fine, often we write specs that fail using the content in the issues such as the characters the person was typing when the issue occurred.

So either is fine, either just identifying and writing up which characters/character sets are failing, or actually writing specs that include those character/character sets and fail.

**Comment by kumarrishav** [comment]
@kevinsawicki  How text rendering happends in atom. I mean do it (codes) exists in atom core or as a separate package. Related Links would be useful 
Thanks

**Comment by bkeepers** [comment]
@kumarrishav Thanks for your interest in Atom. I hope you were able to dive into the atom source code and find answers to some of your questions.

I'm going to close this since the application deadline is now passed.
