### ISSUE TITLE
Gsoc15:Fixing misclassified language in Linguist

### ISSUE THREAD

**Issue by devtrace404** [github/gsoc#54]
Hello everyone
I am reading Linguist code and I am getting little familiar with it. Can anyone please tell me now what should I do if I want to fix a misclassified Language. It would be great if you could please mention which are files should I read for that.
Thank You
Pawandeep Singh

**Comment by bkeepers** [comment]
Hi, thanks for getting in touch. The linguist [contributing guide](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-a-misclassified-language) is probably a good place to start. Let me know if you have any questions after looking at that.
