### ISSUE TITLE
Improve printing support of Atom Shell

### ISSUE THREAD

**Issue by bugisup** [github/gsoc#56]
Hi. I'd like to participate in improving Atom Shell. This idea is very interesting for me. What can I do to be selected on this task? Thanks.

**Comment by zcbenz** [comment]
The printing related code comes from Chromium, so to get started with Atom Shell you should first get more familiar with Chromium's architecture: http://dev.chromium.org/Home.

**Comment by bugisup** [comment]
I mean what I need to do from organization side, I'm familiar with Chromium, I have experience with that around ~2.5 years

**Comment by zcbenz** [comment]
@bugisup The only requirement for you is to write a proposal on GSoC's website.

**Comment by bugisup** [comment]
Hi again. I have submitted the proposal on gsoc site. Will be I considered for participating?

**Comment by zcbenz** [comment]
@bugisup It depends on all team members' decisions and the slots we get from Google, so it is hard to say until the final result is published.

**Comment by bugisup** [comment]
Thank you for the fast answer. Is there anything that can increase my chances? I'm able to send my proposal to here, maybe you and other members would ask me something or clarify. I really want to participate, because it's a interesting task for me. Maybe I should start fixing this bug immediately?

**Comment by zcbenz** [comment]
I think the proposal is the most important factor, contributing to the project would help a lot, but it is probably too late to do it now.
