### ISSUE TITLE
New proposal: Coding "GitHub News"

### ISSUE THREAD

**Issue by adrianblanco** [github/gsoc#60]
# Github News

> The news hub of Github 
##### Opportunity

Journalism projects and activities like open data, coding, visualizations, news apps are each day more important in journalism. As a result lots of media -for example, La Times, NYT, The Guardian , The Times- are opening their GitHub accounts to share the code and stuff they develop.
##### Proposal

The idea is to create a hub, an space in which all journalistic initiatives in GitHub are tracked, explained and showed. 
The second part apart from taking all interesting resources is to create a lab on this space to develop new tools. Some ideas for new tools I would like to work in during this period: 
-news app to create visualizations with open code (charts, bars...) easy to use, customize and share.
-news app to create context: similar to a timeline but with the interface of a calendar.
## Languages to put in practice

Javascript, Markdown, HTML, CSS
## Who am I?

I am Adrian Blanco, a journalism student based in London and working as an intern for an international news agency. I consider myself a junior data journalist moving to journocoder. I want to improve my code skills and contribute to generate a journalism community in coding.
##### Coding level

Medium-advanced HTML and CSS, learning Javascript and Python by my own, taking part in courses and reading documentation. I do not have the skills of a pro developer but I have the intention and the passion to improve my knowledge.
##### Benefits for me

-Online. I can assume it without forgetting my current occupations.
-Work with a mentor to learn and develop the project.
-Apply coding to journalism and improving my level of Javascript and Python.
-I want to code properly. All my senses on the project.
## Benefits for the community

A reference site where journalism students interested in code, hacks, hackers, journocoders and everyone can go to see what is being done in journalism. Share knowledge, initiatives, news apps, content and create open tools to improve the level of the simbiosis between journalism and coding. 
## Documentation

Some interesting profiles
NYT: https://github.com/NYTimes
LA Times: https://github.com/datadesk
FT: https://github.com/ftlabs
The Times: https://github.com/times
For Journalism: https://github.com/ForJournalism
J++: https://github.com/jplusplus
The Guardian: https://github.com/guardian

Tools
Chart Builder: http://quartz.github.io/Chartbuilder/
AxisJS: http://times.github.io/axisJS/#/

Readings
http://knightlab.northwestern.edu/2013/06/13/getting-github-why-journalists-should-know-and-use-the-social-coding-site/
http://www.pbs.org/mediashift/2015/01/why-journalism-students-need-a-baseline-understanding-of-coding/

**Comment by johndbritton** [comment]
@a-br While I personally think this is a cool idea for a project, I don't think it fits well within the framework of Google Summer of Code.

The program requires that you contribute to an existing open source project, and this would be an entirely new project.

**Comment by adrianblanco** [comment]
@johndbritton Thanks for the feedback!
