### ISSUE TITLE
Can I make more than one proposal?

### ISSUE THREAD

**Issue by youtux** [github/gsoc#61]
/cc @mikemcquaid
I would like to contribute to some of the Homebrew's ideas. Is it possible to submit more than one proposal?

**Comment by MikeMcQuaid** [comment]
@youtux You _can_ submit more than one proposal but to save both our time I'd probably advise talking through ideas here first and I can give you a :+1: on the best proposal to make.

**Comment by youtux** [comment]
Actually what I meant is that I would like to make a proposal for three of the four ideas listened in the Homebrew section, not to add more ideas.
From https://github.com/github/gsoc/issues/57 I see that I'm not supposed to make my proposal public, so can I send to you my proposal to have a feedback?

Thank you!

**Comment by MikeMcQuaid** [comment]
@youtux You can email it privately to me at mike@mikemcquaid.com and I'll take a look if you like. I'd suggest picking one project, though. If you're looking for any guidance there then "Officially support using Homebrew without Xcode/CLT" and "Application packages should include all their dependencies" I haven't seen any proposals for yet so might be slightly more likely if we got a million slots but it's obviously hard to say at this stage (and we don't get a million slots :trollface:).
