### ISSUE TITLE
Homebrew: Remove a formula along with it's dependencies, sensibly.

### ISSUE THREAD

**Issue by mohakshah** [github/gsoc#62]
I have been looking into a good method to implement a way to remove a formula's dependencies along with that formula for some time. Apart from recursively checking for the dependencies, I would like to use otool (as suggested by @jacknagel on https://github.com/Homebrew/homebrew/issues/7465) and remove just the dependencies that no other formula has linked itself to. Of course the removal of these dependencies would be optional (Sort of like apt on debian/ubuntu).

/cc @mikemcquaid

**Comment by MikeMcQuaid** [comment]
@mohakshah `otool` would be one solution but we also might want to store the dependencies in the `INSTALL_RECEIPT.json` and run through them instead. I'd definitely consider a proposal doing this for a project though :+1:
