### ISSUE TITLE
GSoC: GitHub command line client

### ISSUE THREAD

**Issue by lejenome** [github/gsoc#64]
**About the Idea:**
Having a GitHub command line client will be very useful and will make it easier to check issues and pull requests without living the console and to locally automate work without the need to webhooks for simple uses cases.
The idea is not to duplicate Hub or webhooks. It's just to complete Hub and replace most common GitHub web site services with command line interface using GitHub API.
- view issues status and milestone progress from the shell
- open/close/merge issues and pull requests.
- some statics and maybe graphs.
- offline support.

All the suggested features are based on may simple use of GitHub. But it should be adopted for big organization and huge projects needs first.
An other part of the project is developing a standalone C lib for GitHub API.

**About Me:**
I'm Moez Bouhlel. First year Computer Science Student at computer science department at Faculty of Science of Sfax. My coding skill are advanced Bash, medium C and JavaScript with basic knowledge of python and ruby. I'm planing to develop GitHub cli client on C.

NOTE: I was planing to propose this idea a couple days ago. But I noticed you refused iOS client idea because GSoC disallows starting new projects. But after reading ToS and discussion with few folks at #gsoc channel, it's up to the monitoring organization as long it's a coding project.

**Comment by MikeMcQuaid** [comment]
> NOTE: I was planing to propose this idea a couple days ago. But I noticed you refused iOS client idea because GSoC disallows starting new projects. But after reading ToS and discussion with few folks at #gsoc channel, it's up to the monitoring organization as long it's a coding project.

It is up to the organisation but as an organisation we're not accepting new projects I'm afraid (particularly as this overlaps heavily with `hub`). Sorry!
