### ISSUE TITLE
Homebrew: Packaging dependencies inside the formula's bottle

### ISSUE THREAD

**Issue by mohakshah** [github/gsoc#65]
Wouldn't including the runtime dependencies _inside_ the Keg create several copies of the same libraries?  I guess that wouldn't be a problem for most libs since they are quite tiny compared to modern storage media. Is that right or am I thinking about it wrong?

/cc @mikemcquaid

**Comment by MikeMcQuaid** [comment]
Yes, there'd be multiple copies of the same libraries. This is not actually much of a problem as they are so small but we could potentially optimise this case with hard links if necessary.
