### ISSUE TITLE
proposal feedback

### ISSUE THREAD

**Issue by ghost** [github/gsoc#66]
So I submitted my proposal on melange a couple of days ago, and haven't received any feedback. Is it that bad.... even then, please feel free to criticize anything that you don't like, and think it can be improved, so I can improve my chances of getting selected.

From my side I just have the one question right now (also the very first line of my proposal), is it ok to have the summary of the proposal in melange with the full thing on a secret gist, or do i need to redo the whole thing inside melange ?

Also note that based on #57, students are not supposed to email mentors unless they explicitly tell the students to do so (I think). So if this something that needs to be discussed via email, please comment with your email address.

Cheers!

/cc @jlord @zcbenz @kevinsawicki @shana

**Comment by MikeMcQuaid** [comment]
Yeh, it's looking good thanks @suyash! We're currently just reviewing all the incoming proposals. Nothing  needs to be changed in yours. Thanks!

**Comment by ghost** [comment]
@mikemcquaid , there is an update that I want to notify about, regarding my proposal, that I have added on my secret gist in the comments. I am pinging you here because gist doesn't have a notification mechanism (to my knowledge). Just wanted to make sure that you got it.
