### ISSUE TITLE
Is Fixing a misclassified language a part of Idea List for Linguist in Gsoc15

### ISSUE THREAD

**Issue by devtrace404** [github/gsoc#67]
I read about Linguist ideas List on  https://github.com/github/gsoc
This page does not have idea of misclassified language
Then I read complete contribution list about Linguist on  https://github.com/github/linguist/blob/master/CONTRIBUTING.md
This page says it has misclassified language as idea list
I am confused..

**Comment by MikeMcQuaid** [comment]
It is not but improving the accuracy using is a potential project: https://github.com/github/gsoc#weighted-scoring-for-detection-strategies
