### ISSUE TITLE
What is the use of Sample folder in Linguist 

### ISSUE THREAD

**Issue by devtrace404** [github/gsoc#68]
I came across Sample folder in Linguist and I think it has nothing to do with Linguist it is just for the developer to get some hand with that language

**Comment by nemesiscodex** [comment]
The Sample folder contains the dataset that may be used to make the classifier smarter. Acording to https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-a-misclassified-language

**Comment by pchaigno** [comment]
@pawandeep2155 - @nemesiscodex is right. It is used to train the Bayesian classifier. It is also used in many tests (see the `tests` folder).
