### ISSUE TITLE
What do you expect in the proposal of Weighted scoring for detection strategies for Linguist

### ISSUE THREAD

**Issue by devtrace404** [github/gsoc#69]
I want to contribute to Linguist in the " Weighted scoring for detection strategies " idea,
I read its detail on https://github.com/github/gsoc .
 Can you please tell what really do you want / what do you expect from this idea for contribution which could be implemented in 3 months.

**Comment by bkeepers** [comment]
Hi @pawandeep2155. I think the links in the description adequately described the problem.
