### ISSUE TITLE
Feedback for GSoC proposal

### ISSUE THREAD

**Issue by Projjol-zz** [github/gsoc#72]
HI!
I'd submitted my proposal a few days back and I haven't received any update regarding it. I understand it must be tough given the huge volume of proposals GitHub would receive, but since only 5 days remain for the application period to close, it'll be great if I could receive pointers regarding my proposal, thereby letting me edit it suitably and improve my chances of getting selected.

Thank you!

cc @kevinsawicki

**Comment by MikeMcQuaid** [comment]
Hi @Projjol, I've commented in Melange. Thanks!

**Comment by Aakash1312** [comment]
This issue is closed. Does this mean that I can' t send proposal?

**Comment by MikeMcQuaid** [comment]
@aprogen No, sorry, it just means I've resolved the question here. You can sent a proposal in Melange.
