### ISSUE TITLE
support for backup organizations

### ISSUE THREAD

**Issue by ghost** [github/gsoc#74]
So I was hanging out in #gsoc yesterday, when I had this conversation

![1](https://cloud.githubusercontent.com/assets/4389751/6850297/5aeabf2e-d3fe-11e4-98e2-5c316d2f88ce.png)

And if that wasn't cryptic enough, what actually got me worried was another conversation

![2](https://cloud.githubusercontent.com/assets/4389751/6850299/609cd09c-d3fe-11e4-8a9b-e9a13599a8bc.png)

And the last comment is super uncomfortable. So the question that I want to ask is this

While evaluating proposals, will GitHub take into consideration the fact that a student may have applied to backup org(s), in case GitHub doesn't get enough slots, or is that not a factor at all. The reason this is important is because some orgs do that, and others [ask for that in the proposal template](https://github.com/BuildmLearn/BuildmLearn-Toolkit/wiki/Guidance-for-Students#project-proposal) (but GitHub hasn't so far).

If the answer is yes, do the students need to revise their proposals to include this.

Again, I am following #57, and opening this as an issue, but if this needs to be discussed via email, please comment with your email address.

Cheers!

/cc @shana @mikemcquaid

**Comment by MikeMcQuaid** [comment]
I think that probably won't be a factor for us but @shana might have a better idea. Regardless, I think we can get in touch nearer the time if this is an issue.

**Comment by bkeepers** [comment]
We'll definitely be in touch if that becomes an issue.
