### ISSUE TITLE
Issue regarding change in Linguist's ideas specification

### ISSUE THREAD

**Issue by rootAvish** [github/gsoc#75]
Hi,

I had submitted a proposal about a week back regarding the idea of using grammar bundles for tokenization in Linguist, which was one of the two original ideas proposed by you guys. Around the same time as I submitted the proposal, the ideas list was changed with #71, and the new list did not contain the original two ideas anymore. So, my question is, are the original two ideas considered scraped now, with you aiming for what sounds like essentially a complete re-write of Linguist? (which I suppose is based off [linguist 2205](https://github.com/github/linguist/issues/2205) and [linguist 2237](https://github.com/github/linguist/issues/2237))

What I'm really trying to say is would this mean that the proposal I or anybody else for that matter submitted for the original idea in the dead now?

If that indeed is the case, I would've liked it if you guys clarified the same _before_ the application period started, considering one had to invest considerable time and energy in understanding the existing project and formulating a plan for the same, since the way I see it the original ideas are essentially "blue-sky" proposals now?

/cc @arfon @bkeepers

**Comment by rootAvish** [comment]
My concern with the issue is that because of this change that took place, I had to make significant changes to my proposal at the very last minute, to add details about how I would go about implementing the extended task at hand. 

I ask that you please review the latest iteration of the proposal and not judge it on the content that was first submitted by me, in case you've already gone through it. Even though it comes at the closing moments of the application period. Thanks.

**Comment by MikeMcQuaid** [comment]
> I ask that you please review the latest iteration of the proposal and not judge it on the content that was first submitted by me, in case you've already gone through it. Even though it comes at the closing moments of the application period. Thanks.

Don't worry, we'll be sure to judge your proposal based on the latest version. I'm really sorry for the inconvenience here and for messing you around.
