### ISSUE TITLE
Is it possible to propose a topic other than 4 areas defined in the idea page.

### ISSUE THREAD

**Issue by kareekij** [github/gsoc#76]
I was wondering if I propose another topic which is outside the area which is defined in the idea page, do I have a chance to be selected?

I would like to conduct the research in cloud computing area. I have an idea to implement secured multi-cloud system. Is it possible to propose to GitHub?

**Comment by MikeMcQuaid** [comment]
Sorry, no, it needs to be on one of our open-source projects listed in the README and is most likely to be selected if it's one of the projects we've suggested. Thanks!
