### ISSUE TITLE
Proposal feedback for Atom

### ISSUE THREAD

**Issue by octref** [github/gsoc#77]
I only submitted my proposal yesterday (sorry), but I spent many hours on it and I'd really like to hear some feedback before the application closes.

@kevinsawicki
Can you take a look at it? Thanks.

@mikemcquaid 
It seems kevin is very busy, and I noticed you seem to be reviewing proposals on behalf of other mentors. Do you mind taking a look at mine? Thanks!

/cc @mikemcquaid @kevinsawicki

**Comment by MikeMcQuaid** [comment]
I've reviewed your proposal and it looks good, thanks @octref. I don't think any changes are needed.
