### ISSUE TITLE
GSoC Project Proposal

### ISSUE THREAD

**Issue by yvtheja** [github/gsoc#78]
Hi,

I have submitted my project proposal on melange but I didn't get any updates or feedback on the proposal. Actually, do I need to wait for any comments on the proposal ? And also I have some UX needs for my project, so, whom should I contact for UX part ? Please review my proposal and let me know if I need to provide still more information.

Thank you.

**Comment by MikeMcQuaid** [comment]
We'll ask any questions we need on the proposal itself. Thanks!

**Comment by yvtheja** [comment]
@mikemcquaid , I didn't get any feedback on my proposal. I have been mailing @kevinsawicki but he seems busy. Could you please review it ?

Thank you.

**Comment by MikeMcQuaid** [comment]
We'll be reviewing proposals over the next two weeks, thanks.

**Comment by yvtheja** [comment]
@mikemcquaid , Thanks for the information :)

**Comment by yvtheja** [comment]
@mikemcquaid , I didn't get any feedback on my proposal, could you please provide me ?

Thank you.

**Comment by MikeMcQuaid** [comment]
@ythej Reviews will be done through the GSoC system. We're probably not providing much more feedback because the edit deadline has passed. Sorry!

**Comment by yvtheja** [comment]
@mikemcquaid , I have this message shown on the top of my proposal,

"Content of this proposal is not editable at this moment, because student application period is over. If you still need to make some changes, please send a comment to the organization. They can enable modifications for this proposal. "

I think we can still edit the proposal if the changes are still needed. Or I can provide the information needed in comments or through my blog which I have mentioned as additional info in my proposal. I believe I have put it very detail with all the requirements needed.

Please provide the feedback on my proposal, I have been waiting and mailing since three weeks but there is no single reply.

Thank you.

**Comment by MikeMcQuaid** [comment]
@ythej I'm sorry but we're past that stage in the process.

**Comment by yvtheja** [comment]
@mikemcquaid , Okay, I will wait for the results. Please make sure that my proposal is evaluated atleast.

Thanks for your reply ! :)
