### ISSUE TITLE
Mockingbird check-in: May 26

### ISSUE THREAD

**Issue by bkeepers** [github/gsoc#81]
Here are the notes for our check-in with @lazywei, @vmg and @arfon on https://github.com/lazywei/mockingbird

Progress:
- tokenizer has been rewritten in Go
- @vmg says code and tests look :+1: 

Next:
- need to find code samples of a known quantity
  - Rosetta code has a lot of samples: https://github.com/github/linguist/pull/2117
    - They may not be great since they are all solving the same problem and may not reflect real-world samples
    - …but, it's a place to start
  - Could find samples from GitHub with vim/emacs mode lines
    - [find some with search](https://github.com/search?utf8=%E2%9C%93&q=vim+set+filetype+OR+ft&type=Code&ref=searchresults), but a GitHubber could also write a scanner to look through all public projects for files with a valid modeline

**Comment by arfon** [comment]
:+1: thanks for posting these.

**Comment by lazywei** [comment]
wow, cool! Thanks for the note :D

And it's nice to meet you guys again :-)

-- Chih-Wei (Bert)
