### ISSUE TITLE
Contributing to Github Project. (Very new to FOSS)

### ISSUE THREAD

**Issue by prastut** [github/gsoc#82]
Hi to all the Github Contributors,

I am Prastut Kumar and I am currently doing my undergrad from Vellore Institute of Technology, Chennai Campus, India in the field of Computer Science and Engineering

I wish to contribute to this project, my very first Open source project, because I liked the concept(duh..its Github). Well liking the idea doesn't mean much, and I wish to contribute as a front-end developer. I have basic knowledge in HTML, CSS, Js,C, C++ and would wish to sharpen my skills by writing lots of code for the Github Community (Read: Quantity beats Quality). I have heard that the Open source community is a very helpful, and I hope if any doubt pertains, I would be guided to the right path.

With best regards
Prastut.

**Comment by MikeMcQuaid** [comment]
Hi Prastut, I'm afraid Google Summer of Code has already started so you wouldn't be able to work with us there. Sorry!

**Comment by pchaigno** [comment]
@prastut You're always welcome to contribute to any open source project though. And being an open source contributor would greatly help your application for GSoC 2016 next year ;)

**Comment by prastut** [comment]
My objective of coding is purely learning! Sorry if I didn't clearly made my purpose clear. (I want to contribute without a GSOC blade hanging over my head. :p)
I want to start contributing as soon as possible. From where do I start was my question to all the fellow contributors.

**Comment by pchaigno** [comment]
@prastut
1. Find a project you want to contribute to. 
2. Build it from sources.
3. Read the documentation.
4. If you find any issue during the installation, try to fix it (don't forget to follow the project's rules).
5. Find an issue on the repo that you think you can fix and fix it!
6. Improve the documentation.
7. Continue :smile:
