### ISSUE TITLE
Mockingbird check-in: 9 June 2015

### ISSUE THREAD

**Issue by arfon** [github/gsoc#83]
Here are notes from the meeting between @arfon and @lazywei on https://github.com/lazywei/mockingbird

**Progress:**
- Bag-of-words construction  & libsvm format conversion complete and in [`develop`](https://github.com/lazywei/mockingbird/tree/develop) branch.
- Libsvm reader implemented
- Documentation for pulling Rosetta code samples [written](https://github.com/lazywei/mockingbird/commit/6013e43d639e134c6549e8641849b7d437a90cc8)

**Next up:**
- Implement naive Bayes classifier (same as Linguist's)
- Set up Travis-CI
- Spend some more time thinking about packaging tools.

:zap: :rocket: :boom:

/ cc @vmg @bkeepers

**Comment by vmg** [comment]
Shit, I missed this. Sorry @arfon!

As I told @bkeepers in Chat, there _is_ a performance issue in the tokenizer, but I'm gonna take care of it (eventually), so @lazywei should keep working as usual and making progress.

**Comment by lazywei** [comment]
Just want to add one more next up item:
- After implementing the NB classifier, we can start doing some comparison with old linguist classifier -- both memory usage and accuracy.

Thanks @vmg for having my back on the performance issue :dart:
