### ISSUE TITLE
GSoC PLZ participate in my Open Source Research

### ISSUE THREAD

**Issue by nalasbali** [github/gsoc#87]
Hi, 

I would like to invite you to participate in my PhD research which is about contributing to Open Source to modernize Computer Science education. The survey will take few minutes but will be of great value to my research as i need direct evidences from OS users like you, plz, to do my research.

I hope you will be happy to participate by clicking on the related link to take the suitable survey & feel free to answer any number of questions (will be much help if you can answer all):

Here you are the link to the mentor's survey: https://www.surveys.unsw.edu.au/f/161600/2b06/
Here you are the link to the student's survey: https://www.surveys.unsw.edu.au/f/161584/5d1e/
Here you are the link to the educator's survey: https://www.surveys.unsw.edu.au/f/161596/1191/
Here you are the link to other experts & professionals from the OS industry: https://www.surveys.unsw.edu.au/f/161607/11a8/

[Participant Implied Consent Statement.pdf](https://github.com/github/gsoc/files/109213/Participant.Implied.Consent.Statement.pdf)

"Please support my PhD research by circulating this invitation and mention it to your friends to reach SoC educators, students, mentors & other experts & professional interested in the OS field"

Many thanks in advance,,
Nada Alasbali
PhD of Computer Science & Engineering, UNSW

**Comment by MikeMcQuaid** [comment]
Thanks and good luck with your PhD! I'm going to close this out as people watching this repo will have seen this notification now and the links and hopefully some fill it out.
