### ISSUE TITLE
GSoC 2016

### ISSUE THREAD

**Issue by naveenjafer** [github/gsoc#88]
Has Github applied as a mentoring organization for the year 2016?

**Comment by MikeMcQuaid** [comment]
Hi @naveenjafer! We haven't announced anything yet but when we do it'll be on this repository. Watch this space!

**Comment by naveenjafer** [comment]
@mikemcquaid  Thank you! Eagerly looking forward to news on the same.

**Comment by naveenjafer** [comment]
Hi @mikemcquaid  No announcements yet? Hope that we get positive news by 19th of this month.

**Comment by hackerkid** [comment]
@naveenjafer You will get notification if any announcement has been made as you are watching the repo.

**Comment by OrkoHunter** [comment]
Or we could just till Google announces the org list.

**Comment by bkeepers** [comment]
We have applied to GSoC 2016. We will open an issue in this repository with details once Google announces the organizations.
