### ISSUE TITLE
Information about "Improve Atom's parser performance"

### ISSUE THREAD

**Issue by tehmas** [github/gsoc#9]
The project idea sounds interesting. I looked at the relevant issues which were updated today in the README file but can I get some more additional details about it? The "summary" seems to be too less about the nature of the project.

**Comment by johndbritton** [comment]
@Tehmas did you read the two linked issues: https://github.com/atom/atom/issues/979 and https://github.com/atom/atom/issues/1667? They document cases where performance is a problem.

**Comment by tehmas** [comment]
@johndbritton Thanks for replying. Yep I read them like I said in my first post. What I am not clear about is that are we required to find out the issues our selves and work on them or we will have to work on already found performance issues which haven't been fixed yet?

**Comment by johndbritton** [comment]
> are we required to find out the issues our selves and work on them or we will have to work on already found performance issues which haven't been fixed yet?

A successful proposal would likely include a few target issues and ways to improve their performance. @kevinsawicki might be able to say more.

**Comment by kevinsawicki** [comment]
> What I am not clear about is that are we required to find out the issues our selves and work on them or we will have to work on already found performance issues which haven't been fixed yet?

The two most important issues to address are performance on files with long lines of text and also large files (over 2MB) in size.

So those are the two really well known issues but there may be other to address which are also really important.
