### ISSUE TITLE
Classroom - Enhanced user management

### ISSUE THREAD

**Issue by johndbritton** [github/gsoc#90]
_Aside from the projects listed here, we are open to other proposals and ideas. Take a look at issues labeled [feedback](https://github.com/education/classroom/labels/feedback), [feature-request](https://github.com/education/classroom/labels/feature-request), [enhancement](https://github.com/education/classroom/labels/enhancement), and [help-wanted](https://github.com/education/classroom/labels/help-wanted) for ideas._

About Classroom:

[Classroom for GitHub](https://classroom.github.com) is an [open source](https://github.com/education/classroom) tool for managing programming coursework on GitHub. The app enables teachers to distribute starter code to students, automatically creating repositories and managing access control for students. It also provides teachers with an easy way to get an overview of their students' submissions made on GitHub.

Summary:

Classroom would benefit from improved user management. At present, students are only identified by their GitHub usernames, making it somewhat difficult for teachers to map accounts to their human students. Additionally, teams for group assignments are formed on-the-fly, as students accept assignment invitations. For this project we'd like to see a comprehensive plan to improve user management in the application allowing teachers to require a specific piece of information (like a student identifier) when accepting an assignment invitation for the first time in a class. To address the problems with group assignments we'd like to build out an interface to manage teams for assignments so that teachers can pre-determine groups and reassign members as needed.

Expected Outcome:
- A straightforward way for teachers to link GitHub usernames to the students in their course roster is implemented.
- An interface for managing teams for group assignments is implemented.
- Additional goals set in the accepted mentee's application are met.

Skills: Ruby, Rails, RSpec, Testing, HTML, CSS, JavaScript

Relevant issues:
- [Student identifier (#448)](https://github.com/education/classroom/issues/448)
- [Staff assigned groups (#415)](https://github.com/education/classroom/issues/415)
- [Team management for administrators (#292)](https://github.com/education/classroom/issues/292)
- [Add ability to auto-invite students to a team (#459)](https://github.com/education/classroom/issues/459)

Primary mentors:
- @johndbritton
- @tarebyte

Supporting mentors:
- @mkcode
- @jasonlong

**Comment by Boggartfly** [comment]
@johndbritton and @bkeepers I'm more keen to work on this idea for GSOC 2016. As I understand GitHub has been accepted to the program this year. I have a fair idea of what can be done to solve this problem. What do you guys think about this as a GSOC project?

**Comment by johndbritton** [comment]
@Boggartfly It looks like we were accepted. Applications will open through the Google Summer of Code site on 14 March. This would be a great project to propose.

**Comment by prastut** [comment]
@johndbritton To verse myself with the codebase, can I start working on this project?

**Comment by johndbritton** [comment]
@prastut Pull requests are welcome, please be sure to read the guidelines for contributing and include tests with any code changes.

**Comment by prastut** [comment]
@johndbritton I have my dev env setup and wish to work on this project. As a fan of Don Norman's work in cognitive science, I believe I can bring this home. How do I prove myself that I am a worthy candidate for this project? There aren't any entry-level bugfixes or issues on which I could work on so therefore asking.

**Comment by johndbritton** [comment]
You can find a list of open issues at https://github.com/education/classroom/issues, especially issues labeled `help-wanted`. If you have other ideas for small things to work on before you propose a project, feel free to open an issue on the repository to discuss.

**Comment by catchabhisek** [comment]
@johndbritton 
Sir, 
I am a node.js developer I want to work with you on this project. How do I prove myself as a worthy candidate for this project ? I have prepared a sub-project i.e Notification Service related to your idea of project: classroom. Sir, shall I push the sub-project in github.

**Comment by johndbritton** [comment]
> How do I prove myself as a worthy candidate for this project ?

@Abi-Abhisek A good place to start is to get the project running locally and sending a pull request for one of the issues labeled [help-wanted](https://github.com/education/classroom/issues?q=is%3Aissue+is%3Aopen+label%3Ahelp-wanted).

> shall I push the sub-project in github.

If you post your code in a repository on your account and share a link in your application, that would be useful to see.

**Comment by catchabhisek** [comment]
@johndbritton 
Sir,
Your existing web-application is in ruby on rails. I am a node.js app developer . So, Can I make one of my own version of auto-complete field using node.js. I will create a repository in response to it ??

**Comment by johndbritton** [comment]
> Your existing web-application is in ruby on rails. I am a node.js app developer . So, Can I make one of my own version of auto-complete field using node.js.

If you work on this project, you'd need to learn Ruby on Rails, however showing your Node.js code would be useful for evaluating your application anyways.

**Comment by catchabhisek** [comment]
ohk. Thank you sir.

**Comment by tarebyte** [comment]
This was taken on by @dinever for Google Summer of Code 2016 and is currently in progress.
