### ISSUE TITLE
Classroom - Explicit assignment submission and due dates

### ISSUE THREAD

**Issue by johndbritton** [github/gsoc#91]
_Aside from the projects listed here, we are open to other proposals and ideas. Take a look at issues labeled [feedback](https://github.com/education/classroom/labels/feedback), [feature-request](https://github.com/education/classroom/labels/feature-request), [enhancement](https://github.com/education/classroom/labels/enhancement), and [help-wanted](https://github.com/education/classroom/labels/help-wanted) for ideas._

About Classroom:

[Classroom for GitHub](https://classroom.github.com) is an [open source](https://github.com/education/classroom) tool for managing programming coursework on GitHub. The app enables teachers to distribute starter code to students, automatically creating repositories and managing access control for students. It also provides teachers with an easy way to get an overview of their students' submissions made on GitHub.

Summary:

Assignment submission and due dates are currently implemented through social constructs in Classroom. Many teachers require students to make sure code to be graded is published and merged to the master branch of their assignment repository by the specified deadline, but there is no technical enforcement of the deadline or the submission process. For this project we need to implement a way for students to explicitly "submit" their work to be graded as well as a way for the system to record the submission time and if it was before or after the submission deadline. A novel approach that we've been considering is to consider pull requests merged to the default branch as submissions and record the timestamps of the merges using webhooks from GitHub. We could expose the due date status to students via the Commit Status API to display "on time" or "late statuses" next to the merge button like a typical continuous integration status.

Expected Outcome:
- A straightforward way to specify (and modify) due dates for assignments is implemented.
- A way for students to explicitly submit their work multiple times is implemented.
- Submission timestamps and commit identifiers are recorded for submissions by the student.
- "on time" and "late" submission status is reported to the student accurately during the process.
- Additional goals set in the accepted mentee's application are met.

Skills: Ruby, Rails, RSpec, Testing, HTML, CSS, JavaScript

Relevant issues:
- [Adding a due date for assignments (#379)](https://github.com/education/classroom/issues/379)

Primary mentors:
- @johndbritton
- @tarebyte

Supporting mentors:
- @mkcode
- @jasonlong

**Comment by moizsajid** [comment]
@johndbritton This seems like an interesting project to work on. However, I have very little experience with Ruby. Is this project going to work out well for me?

**Comment by johndbritton** [comment]
> This seems like an interesting project to work on. However, I have very little experience with Ruby. Is this project going to work out well for me?

I think it would be helpful if the student had some Ruby experience. I'd recommend trying to get the app running locally and making an attempt to fix a small bug or make a small change. I think that's a reasonable minimum bar for being considered for this project.

**Comment by leonnardo** [comment]
@johndbritton I have interest in this project (or any other issue of Classroom) for GSoC. How can I start?

**Comment by johndbritton** [comment]
@leonnardo As mentioned above, you can start by getting the app running locally and submitting some bugfixes other small improvements.

> I think it would be helpful if the student had some Ruby experience. I'd recommend trying to get the app running locally and making an attempt to fix a small bug or make a small change. I think that's a reasonable minimum bar for being considered for this project.

**Comment by amitojsingh** [comment]
@johndbritton 
Hello, 
I forked the classroom repository as it was written in the contributing guidelines and successfully running this app locally on my system. now what to do next? Can I have list of bugs?
cheers!

**Comment by johndbritton** [comment]
@amitojsingh There's a list of issues at https://github.com/education/classroom/issues, feel free to dive in to any that are labeled `help-wanted` or open an issue in the repo to discuss other ideas you'd like to work on before submitting your proposal.

**Comment by leonnardo** [comment]
@johndbritton,

Hello,

I tried to setup a development environment in my machine but in last step (run server) I got this error and I can't find a solution: https://gist.github.com/leonnardo/06ed3acea0b8569cf595

How can I fix this?

**Comment by tarebyte** [comment]
This was taken on by @cyhsutw for Google Summer of Code 2016 and is currently in progress.

**Comment by sxlijin** [comment]
Linking education/classroom#720 which is the currently open PR for this.
