### ISSUE TITLE
Classroom - Enhanced repository management

### ISSUE THREAD

**Issue by johndbritton** [github/gsoc#92]
_Aside from the projects listed here, we are open to other proposals and ideas. Take a look at issues labeled [feedback](https://github.com/education/classroom/labels/feedback), [feature-request](https://github.com/education/classroom/labels/feature-request), [enhancement](https://github.com/education/classroom/labels/enhancement), and [help-wanted](https://github.com/education/classroom/labels/help-wanted) for ideas._

About Classroom:

[Classroom for GitHub](https://classroom.github.com) is an [open source](https://github.com/education/classroom) tool for managing programming coursework on GitHub. The app enables teachers to distribute starter code to students, automatically creating repositories and managing access control for students. It also provides teachers with an easy way to get an overview of their students' submissions made on GitHub.

Summary:

Classroom manages repositories for assignments in a GitHub organization via the GitHub API. If a user deletes a repository on GitHub, rather than through Classroom, there's no way for us to recreate it. Further, if Classroom is trying to create a repository that already exists, there's no way for us to connect with the existing repository on GitHub. Finally, on the assignment page, a list of student submissions is displayed with links to the repositories on GitHub, but there's no metadata (recent activity, pull requests, issues, last push) shown and there's no easy way to pull down code from all of the students at once. The goal of this project is to improve repository management for all of these cases.

Expected Outcome:
- A manual or automated way to recreate a repository that was manually deleted from GitHub.
- A manual or automated way to connect a new assignment submission in Classroom to a repository that already exists on GitHub with the same name
- Repository listings on assignment views show relevant metadata to better inform teachers of student progress
- Repository listings provide a way to download all submissions in bulk as an archive file or as git repositories using a tool on the client.

Skills: Ruby, Rails, RSpec, Testing, HTML, CSS, JavaScript

Relevant issues:
- [Transfer repositories (#438)](https://github.com/education/classroom/issues/438)
- [Handle repository already exists on GitHub (#319)](https://github.com/education/classroom/issues/319)
- [Ability to clone repositories from assignment submission list (#394)](https://github.com/education/classroom/issues/394)

Primary mentors:
- @johndbritton
- @tarebyte

Supporting mentors:
- @mkcode
- @jasonlong

**Comment by Boggartfly** [comment]
@bkeepers and @johndbritton This is a very interesting project. Is this project eligible for a **GSOC 2016** _(Google Summer of Code)_ submission? I'm thinking of doing that. Please do let me know!

**Comment by johndbritton** [comment]
@Boggartfly [GSoC timeline](https://developers.google.com/open-source/gsoc/timeline) says that we'll know if we are accepted as of 19:00 UTC on 29 Feb.

**Comment by ghost** [comment]
Hello, I am interested in this project. I have got a local installation running. Can you please point me to some beginner bugs to get familiar with the code base.

**Comment by ironmaniiith** [comment]
I found the idea of Github Classroom quiet interesting and would like to contribute to it.
@johndbritton , @tarebyte can you tell me how can I start contributing to it and get involved in the developing community.

**Comment by dasilvacontin** [comment]
Regarding repository metadata, it would be nice if you could tell which repositories pass tests (CI build success) in the repository listing.

Maybe that's what you meant with 'last push'.

**Comment by sahilshekhawat** [comment]
@johndbritton @tarebyte 

> A manual or automated way to recreate a repository that was manually deleted from GitHub.

This part is just about creating a new repository or restoring? If it is about just creating a repository. It should be easy enough. for restoring, I think we can restore issues by saving them in our database (just the title and details) and restore it from there.

> A manual or automated way to connect a new assignment submission in Classroom to a repository that already exists on GitHub with the same name

Existing repo can be anywhere or its owner must be the student who is submitting?

> Repository listings provide a way to download all submissions in bulk as an archive file or as git repositories using a tool on the client.

Does creating a tool like herokubelt which will run locally and will recursively clone assignments will work?

**Comment by sahilshekhawat** [comment]
@johndbritton I am finishing up my proposal, it will be nice if you can clear some of my doubts here. Thanks

**Comment by johndbritton** [comment]
> This part is just about creating a new repository or restoring? If it is about just creating a repository. It should be easy enough.

The goal here is to provide the user a way to recover from the situation where a repository created by Classroom has been deleted. Recovery may be impossible, but replacing the repo with a new one should be relatively easy. How we do it is less important than making sure it's a good experience for the user.

> Existing repo can be anywhere or its owner must be the student who is submitting?

The existing repo would have to be in the Classroom organization. Imagine a case where a student called `student` submits an assignment called `assignment` the resulting repository would be called `student-assignment` if the Classroom organization has a repository by that name, we should probably just connect to that repository and use it instead of creating a new one. Alternatively, we could create a repository with a different name. We just have to handle the case of a name collision gracefully.

> Does creating a tool like herokubelt which will run locally and will recursively clone assignments will work?

Something like that could be good. I actually have been thinking about the idea of implementing this as an Atom plugin as well.

**Comment by sahilshekhawat** [comment]
> The goal here is to provide the user a way to recover from the situation where a repository created by Classroom has been deleted. Recovery may be impossible, but replacing the repo with a new one should be relatively easy. How we do it is less important than making sure it's a good experience for the user.

I agree, creating a new repository is easy. We can recover issues by storing them to Classroom's database but that will increase computation many folds since we will have to keep them in sync. 

> The existing repo would have to be in the Classroom organization. Imagine a case where a student called student submits an assignment called assignment the resulting repository would be called student-assignment if the Classroom organization has a repository by that name, we should probably just connect to that repository and use it instead of creating a new one. Alternatively, we could create a repository with a different name. We just have to handle the case of a name collision gracefully.

I think that it is a design issue but I am more inclined towards creating a new repository because using existing repo might cause an issue. On the other hand, we can create a convention and not let user create/delete repos.

> Something like that could be good. I actually have been thinking about the idea of implementing this as an Atom plugin as well.

Yeah, we can provide many options like Atom plugin that you suggested or cli tool. On the other hand, we can also add feature to download all the assignments as zip using something like [rubyzip](https://github.com/rubyzip/rubyzip) which will remove dependency on atom or cli tools.

**Comment by johndbritton** [comment]
> add feature to download all the assignments as zip using something like rubyzip

We're trying to avoid having the app create assets or need to serve the data, where possible we should rely on the github.com infrastructure as it's much more suited for scalable use. With very large classes (hundreds of students) we could see performance issues on Classroom if we made the archives on our side.

**Comment by sahilshekhawat** [comment]
I agree, then its better to create a client side tool.

Is it fine that I showed up on the last day of deadline? I actually talked to Mike McQuaid during an open source conference and he inspired to me to apply.

**Comment by sahilshekhawat** [comment]
Also, maybe we can extend our client side tool with a desktop app in the future.

**Comment by johndbritton** [comment]
@sahilshekhawat Yes, it's totally fine. I'd suggest you get your application in ASAP so there might be a chance to receive feedback before the deadline.

**Comment by sahilshekhawat** [comment]
For bulk downloading in the web app, can we use a js library like https://stuk.github.io/jszip/documentation/examples.html and recursively create a single zip file using all the repos since github already provides zips for each repo?

**Comment by dasilvacontin** [comment]
Why not have a CLI that clones/pulls all the assignments? Having the actual git repo has multiple benefits:
- what's the current state/version of the repo? am I updated/outdated? just need to check the HEAD
- to update the assignment, only the new commits have to fetched, instead of downloading the whole repository again
- integration with git tools/plugins, e.g.:
  - when browsing assignment, can do `git browse` (or `git browse issues`) to open GitHub repository page (or its issues page) on the browser
  - when browsing a file inside the editor, there's plugins to open that file/commit on the browser, so you can add a comment on a line (feedback is very important)
  - you can use `blame` to tell which student wrote the line (in case of group projects)
  - etc etc
- teacher can push commits to the repo if needed, or easily fork it and send a pull request (all from the command line)
- teacher can create issues from the command line
- etc etc

**Comment by sahilshekhawat** [comment]
yeah, I agree and I am planning to have both a CLI and a webapp feature to download all the submission. webapp feature will be implemented using JSZip and Github API's `archive_url` for individual repos. This feature will provide an easy alternative much like Github own zip download option.

**Comment by sahilshekhawat** [comment]
I have uploaded my project for reference, will be updating it till the deadline. Would love to get any kind of feedback.

**Comment by sahilshekhawat** [comment]
@johndbritton @tarebyte Any feedback on my proposal?

**Comment by johndbritton** [comment]
@sahilshekhawat I'm taking a look at it, but I don't think I will have time to give feedback before the deadline.

**Comment by sahilshekhawat** [comment]
I was wondering if instead of creating a separate command line tool, we can add those functionality to hub itself? @johndbritton what do you think?

**Comment by johndbritton** [comment]
> I was wondering if instead of creating a separate command line tool, we can add those functionality to hub itself?

I don't know if `hub` supports extensions / plugins, but if it does that could be an interesting solution. I wouldn't expect the `hub` maintainers to accept changes specific to Classroom into the main project though.

**Comment by dasilvacontin** [comment]
> I wouldn't expect the hub maintainers to accept changes specific to Classroom into the main project though.

I would be surprised otherwise. You can always make a git alias, in case you wanted to use the CLI ala `git assignment multi-clone 10861471-kipos/test-assignment`.

More functionality could be added in the future, e.g. `git assignment create 10861471-kipos -t "ATM Simulator"` (creates individual assignment named "ATM Simulator" with current git repo as starter code). Though there's a lot of important work to be done in the web client first.

Also, these classroom names are not very CLI friendly... though maybe the 'id' part could be omitted, and hope the user doesn't belong to two classrooms with the same name.

**Comment by jvilk** [comment]
Just to add my own voice in here: I'm using GitHub classroom in a class with 100 students using private repositories. The "importer", which creates the repository for a student, allows the student to _cancel_ the import. When this occurs, we are left with an empty repository in our org account.

If I delete the repository, GitHub classroom will not allow the student to re-import the repository; it links to the deleted repository. To fix the issue, I need to create the repository manually.

It would be nice to have an easy way to re-create repos when this happens, or perhaps to "reset" them.

EDIT: Just realized this is a issue for a potential GSoC project! I found it from Googling. :) I hope someone works on this.

**Comment by johndbritton** [comment]
> The "importer", which creates the repository for a student, allows the student to cancel the import. When this occurs, we are left with an empty repository in our org account.

There's no way for us to disable that functionality, unfortunately. @jvilk Would you mind opening another issue specifically about stopping the user from canceling the import / re-importing in the case of aborting? I think we could side-step the issue by showing a progress bar on the accept page until the import is done.

https://github.com/education/classroom/issues/new

**Comment by tarebyte** [comment]
This was taken on by @cyhsutw for Google Summer of Code 2016 and is currently in progress.

**Comment by tarebyte** [comment]
- [Handle repository already exists on GitHub (#319)](https://github.com/education/classroom/issues/319)
- [Ability to clone repositories from assignment submission list (#394)](https://github.com/education/classroom/issues/394)

Are already done, but [Transfer repositories (#438)](https://github.com/education/classroom/issues/438) is still open for any takers!

**Comment by tarebyte** [comment]
Classroom projects are no longer apart of the selection for GSOC '17. Closing this out to save confusion.
