### ISSUE TITLE
Atom Package to develop Electron Apps

### ISSUE THREAD

**Issue by naveenjafer** [github/gsoc#93]
`Project Proposal`

This project that I would like to work on is an idea based on a Project that that was floated last year as a part of Google Summer of Code  2015 under Atom. The idea is to build a `Atom Package` to develop Electron(Previously called Atom Shell) apps. What I envision is a feature where developers of the powerful Electron framework, get their application up and running in not more than a couple of clicks. The following are the Features that I wish to implement.

1) A set of different boilerplate templates to choose from.
2) A predictions and autocomplete feature of available methods, making use of the powerful autocomplete-plus API built into atom. 
3) Start, deploy and debug applications right from atom.
4) Debugging a few of  the main Processes in Electron is still a bit buggy, but I plan to make use of Node-Inspector to debug Electron apps.(Best way to start pilot tests would be to build it for more stable node js projects)
5) Since Node-Inspector runs on Chrome, I plan to build it on top of the atom-webbrowser package that offers browser like features within atom and would thus enable debugging right from atom.
6) Packaging applications for distribution.

This is a rough draft of the features that I wish to implement. I find the electron framework really powerful and would love to enable more users to develop applications with ease. Current plans are to develop it in atom, as I have already started building modular parts for this project(with current emphasis on running nodejs applications) Atom also provides the flexibility to implement all the features that I have mentioned above. 

I have not been able to get in touch with any potential mentor for this project. 
It would be really wonderful to have a discussion with interested github members regarding the feasibility and roadmap for the same.

Really looking forward to working on this project and improving the application development lifecycle.

**Comment by naveenjafer** [comment]
Hi, @zcbenz  would you be able to help me with this in your spare time. It would be great if you can :)

**Comment by zcbenz** [comment]
@naveenjafer This project looks good to me, but whether we can accept you as a student on this will depend on the slots we get from Google and the student applications we received.

**Comment by naveenjafer** [comment]
Hi, @zcbenz  I understand that Google will allot the slots finally and the importance of the project within the organization will also play an important role. I would love to have a short discussion with a Github member on the same. I have tried the community at discuss.atom.io for the same, but have been unable to evoke much response for the selected queries that I have. The initial direction from experienced electron developers will really help me continue working on pilot modules that would give an idea of the objective of this proposal.

**Comment by naveenjafer** [comment]
Great to see Github as a mentoring organization for Google Summer of Code 2016. Eagerly looking forward to discuss this proposal with potential mentors.

**Comment by naveenjafer** [comment]
Hi @zcbenz , What would be the best place to get in touch with you. I am not sure if my mails have been delivered to your email ID as expected. Would Slack be a good place for the same?

**Comment by zcbenz** [comment]
Hi @naveenjafer, after discussing with the team, we won't have a mentor for this project this year, sorry but I'm closing this.
