### ISSUE TITLE
Hubot support for multiple adapters

### ISSUE THREAD

**Issue by technicalpickles** [github/gsoc#95]
**Summary**:

Hubot uses the adapter pattern to support many chat platforms. Its architecture currently only supports being connected to one adapter. Connecting to additional adapters is simple in theory, but has a lot of details to work through. When a user is interacting with hubot across two connected adapters, there would be an expectation that hubot knows that you are the same human being on both. Naive implementations of multiple adapters would treat these as two separate users, which would work for some use cases, but not all. 

**Expected Outcome**:

A released version of hubot http://npmjs.org/packages/hubot which contains support for multiple adapters. It should have a mechanism, either builtin hubot or available as an external package, for identifying a user across the configured adapters.

The release should maintain semantic versioning, and be a minor point release. New hubot should be able to be configured to use multiple adapters, and existing installs of hubot should work without change

**Skills**: javascript, coffeescript

**Relevant issues:**
- https://github.com/github/hubot/issues/122
- https://github.com/github/hubot/pull/133
- https://github.com/github/hubot/issues/1075
- https://github.com/github/hubot/issues/507

Mentors: @technicalpickles

cc @bhuga

**Comment by bhuga** [comment]
:heart:

**Comment by jackatbancast** [comment]
Since hubot requires an an external package to support roles, would there be any real benefit of integrating recognition of a human across adapters into hubot?

Also, would a sensible way of adding this functionality be to sychronise via a magic cookie and using a key-value store to save the association of users across platforms?

**Comment by technicalpickles** [comment]
> Since hubot requires an an external package to support roles, would there be any real benefit of integrating recognition of a human across adapters into hubot?

I tried to word the expected outcome to suggest that it's pretty likely that it would be an external package to coordinate recognition of humans across adapters, rather than part of hubot's core.

> Also, would a sensible way of adding this functionality be to sychronise via a magic cookie and using a key-value store to save the association of users across platforms?

Can you elaborate on what you mean by synchronizing a magic cookie?

Hubot has a key/value store as part of it's core, which includes information about a user. See https://github.com/github/mentorships/issues/96 for a related project which talks a bit more abou tit.

**Comment by abhishekc-sharma** [comment]
I've gone through the code of the hubot core and that of the two default adapters and feel like I have pretty good idea of how it works now. I have a few questions about what exactly is expected out of this.

What would recognition of users across platforms pertain to exactly ?

And at what stage of interaction with the user is the bot supposed to recognise that it's a user from another platform ? Immediately using some provided details or after the user identifies himself somehow or maybe something else that you have thought of.

Also is this project available for GSoC or is that decision to be made only after reviewing all proposals ?

**Comment by technicalpickles** [comment]
> What would recognition of users across platforms pertain to exactly ?

Here's an example to try to explain. Let's say I wrote a hubot to help maintain hubot (very meta), and wanted it to work in #hubot on IRC and on a (fictional) community Slack account. I could write a script where I tell it about myself (like npm login, github login, etc). That is where hubot's brain comes in, where scripts can save data about a specific user. If I'm `technicalpickles` on IRC, and `josh` on Slack, I would want a way to have hubot that I'm the same person on both, so the scripts that have data about the user work without any other changes. It should be a single user for both those identities. There's some room to explore how to actually connect the identities, but that is a good chunk of what the project is about.

> And at what stage of interaction with the user is the bot supposed to recognise that it's a user from another platform ? Immediately using some provided details or after the user identifies himself somehow or maybe something else that you have thought of.

That is a good question, but I don't have an answer for it yet. I'd consider that part of working through this project.

> Also is this project available for GSoC or is that decision to be made only after reviewing all proposals ?

I'm not sure I follow the entire question. If there are proposals for this project as part of GSoC, they would be considered. Applications for it open up next week and are submitted through Google.

**Comment by abhishekc-sharma** [comment]
Thanks for the reply ! Will think about this more and try to come up with something.

**Comment by abhishekc-sharma** [comment]
@technicalpickles have shared the draft link for my proposal. Looking forward to the feedback :)

**Comment by babhishek21** [comment]
Is this project idea available for **GSOC '17**?

**Comment by MikeMcQuaid** [comment]
GitHub is not participating directly in GSoC 2017. The Homebrew project (which I maintain) has applied to participate this summer: https://github.com/Homebrew/Outreachy-and-Google-Summer-of-Code. Note you'll need access to a Mac to take part. Thanks!
