### ISSUE TITLE
Improved hubot persistence

### ISSUE THREAD

**Issue by technicalpickles** [github/gsoc#96]
**Summary:**

Hubot has supported persistence for a long time. Chat users encountered are saved, with scripts having the ability to recall or change details about the user, in addition to saving more global information.

Internally, this is implemented as a simple javascript object in memory. Through scripts like [hubot-redis-brain](https://github.com/hubot-scripts/hubot-redis-brain) 'support' saving this to redis, but it is very naive. It simply flushes this from in-memory to a specific key in redis, with the value being a serialized JSON object.

This implementation is problematic for a few reasons. First, there have been race conditions in the past that lead to hubots losing their mind (ie they might initialize an empty javascript object, and flush that to redis, rather than reading an existing key). Second, because the brain is constantly being flushed to its data store, that means multiple hubots can use the same datastore without clobbering each other's data.

**Expected Outcome:**

A hubot release with first class support for hubot persistence with a key/value API for brain, and a released version of hubot-redis-brain. The releases should maintain semantic versioning as a minor release, so existing installations can work without change.

There should be updated documentation preferring the key/value API, and deprecation of the old way of using persistence. The default set of hubot scripts should be updated to use the new API.

**Skills:** coffeescript, javascript

**Relevant issues:**
- https://github.com/github/hubot/issues/619
- https://github.com/github/hubot/issues/1010
- https://github.com/github/hubot/issues/963
- https://github.com/github/hubot/issues/787

Mentors: @technicalpickles

cc @bhuga

**Comment by bhuga** [comment]
:heart:

**Comment by byt3smith** [comment]
:+1:

**Comment by nanaeasiedu** [comment]
:+1: Seems like an interesting project I would like to work on

**Comment by burdenless** [comment]
Would it be reasonable to assume that with moving to a more stable and supported form of data persistence, the various configuration options that are specified as environment variables currently may also be moved to persistent storage? Moving the configuration variables to storage might help with other areas of future Hubot development, for instance, with the use of multiple adapters. Keeping track of multiple chat rooms and nicks would be better served using persistent storage.

Just a thought

**Comment by technicalpickles** [comment]
> Would it be reasonable to assume that with moving to a more stable and supported form of data persistence, the various configuration options that are specified as environment variables currently may also be moved to persistent storage?

That is not a good assumption. Environment variables are typically used for configuration, with things like API credentials and things like that. It should be possible to change those at hubot start time without having to talk to a persistent datastore.

**Comment by burdenless** [comment]
Fair enough. Just throwing around ideas of other possible use cases for persistence.

**Comment by nanaeasiedu** [comment]
Most of the issues I looked at seemed to talk about the timing and the way the event emiiters have been mixed up in the adapters, brain and robot. Does this mean that most of the problems with the `brain` and the external scripts persistence arises due to timing and event emitters?

> A hubot release with first class support for hubot persistence with a key/value API for brain, and a released version of hubot-redis-brain.

Don't really get it. Is it that we want to move persistence into the hubot brain code or create an API for it.

**Comment by technicalpickles** [comment]
@ngenerio:

> Does this mean that most of the problems with the brain and the external scripts persistence arises due to timing and event emitters?

That's correct. There are at least 3 event emitters in hubot (robot, adapter, brain) and it is difficult to reason about what fires when, and persistence related things should take place.

> Is it that we want to move persistence into the hubot brain code or create an API for it.

Sorry for the ambiguous language. It's for creating & documenting the API for other things to use.

**Comment by nanaeasiedu** [comment]
So what this project seeks to achieve is to provide a more concise and orderly way to know what happens in `hubot` and when it happens?

And also making sure hubot brain's works in a way to provide consistency??

**Comment by nanaeasiedu** [comment]
All this must take place whiles also supporting #95 because it looks like one can't be done without considering the design of the other?

**Comment by technicalpickles** [comment]
> So what this project seeks to achieve is to provide a more concise and orderly way to know what happens in hubot and when it happens? And also making sure hubot brain's works in a way to provide consistency?

That's right.

> All this must take place whiles also supporting #95 because it looks like one can't be done without considering the design of the other?

Not necessarily. These are both project ideas, but it doesn't mean they will both be accepted and worked on.

This project will care a lot about backwards compatibility with existing hubot installs & scripts, so that project can proceed without an explicit dependency.

**Comment by nanaeasiedu** [comment]
@technicalpickles Understood.

**Comment by nanaeasiedu** [comment]
Currently gone through how the events in hubot works. Will do a write up for this and see where to go from there.

**Comment by Purushottamjoshi** [comment]
Sounds great.....would like to work on this one

**Comment by MikeMcQuaid** [comment]
GitHub is not participating directly in GSoC 2017. The Homebrew project (which I maintain) has applied to participate this summer: https://github.com/Homebrew/Outreachy-and-Google-Summer-of-Code. Note you'll need access to a Mac to take part. Thanks!
