### ISSUE TITLE
Electron - Multiple language support in documentation site

### ISSUE THREAD

**Issue by zcbenz** [github/gsoc#97]
**Summary**:

Electron's [documentation site](https://github.com/atom/electron.atom.io) only supports English for now, though there are translations of the documentations in [Electron's repo](https://github.com/atom/electron/tree/master/docs-translations), they are not showed in the website.

**Expected Outcome**:
- Provide a way to switch between multiple languages in the website.
- Automatically update the website with the documentations in Electron's repo.

**Skills**: Jekyll, HTML, CSS, JavaScript

**Relevant issues**:
- https://github.com/atom/electron.atom.io/issues/51
- https://github.com/atom/electron/issues/2524

Mentors: @zcbenz

**Comment by connorshea** [comment]
I might be interested in this, I have experience with Jekyll, as well as in implementing i18n in Rails. Would it be possible to get more information on this one?

**Comment by johndbritton** [comment]
@zcbenz Is the best person to answer questions about this, but I would encourage you to start putting together a proposal to bring the multi-language documentation to the electron site.

**Comment by chanlvh** [comment]
Wondering if the website is written in Rails?

**Comment by thePsguy** [comment]
@zcbenz, Could you please set up a development challenge for this task? I'm pretty sure this is a task many people could handle really well, given its direct nature.

**Comment by fossygirl** [comment]
Closing per email conversation with @zcbenz
