### ISSUE TITLE
Releases management in GitHub for Visual Studio

### ISSUE THREAD

**Issue by shana** [github/gsoc#99]
### Before you start

**Please read the student manual at http://write.flossmanuals.net/gsocstudentguide/what-is-google-summer-of-code/ and make sure you understand how the program works, how proposals are submitted and all the milestones involved.**

---

_Aside from the projects listed here, we are open to other proposals and ideas. Take a look at issues labeled [feature](https://github.com/github/VisualStudio/labels/feature), [enhancement](https://github.com/github/VisualStudio/labels/enhancement), and [help-wanted](https://github.com/github/VisualStudio/labels/help wanted) for ideas._

---

**About GitHub for Visual Studio**

[GitHub for Visual Studio](https://visualstudio.github.com) is an [open source](https://github.com/github/VisualStudio) tool for managing your GitHub repositories in Visual Studio. 

**Summary**

GitHub provides a way of distributing releases for a repository through the releases page. A release is composed of one or more build artifacts / binary files, a title, a description, and a tag representing the state of the code that produces the binaries. Larger projects use continuous integration services (AppVeyor, Jenkins, etc) to automatically create builds from commits on a repository, which can then be sent to GitHub automatically to create a release, while smaller projects do local builds and need to upload them manually to GitHub whenever they wish to do a release. In the case of smaller projects, it would be handy to be able to automate creating a release directly from Visual Studio, using the build artifacts it produces.

**About the proposal**

Your proposal should include mockups for the UI and the workflow of the feature. It should also include a roadmap of development - try to get down to a week-by-week level (I know it's hard, but it's a good exercise, even if it ends up being adjusted during development). It should include the deliverables for the midterm and end of term.

Any questions and discussions, feel free to ask in the [issue](https://github.com/github/VisualStudio/issues/223) or in the chat (see repo for link).

**Expected Outcome**
- UI for creating new releases and managing existing releases
- Uploading Visual Studio build artifacts to a new or existing release
- Optional nice-to-have: Generating a changelog for the release
- Optional nice-to-have: [For vsix projects] Generating a VS gallery feed for broadcasting new releases
- ... any other things you think might be useful.

**Skills**
- C#
- Visual Studio

**Relevant issues**
- [Publish releases](https://github.com/github/VisualStudio/issues/223)

**Primary mentors**
- @shana

**Comment by devkhan** [comment]
This looks good, I would like to take up this project. Where can we discuss about this project? Is there an IRC channel or Gitter or something?

**Comment by gitexperience** [comment]
I have immense experience on working on Visual Studio and Xamarin with C#, and have contributed a lot to the mono-project , but unfortunately it is not listed in this years' list ..
I will need your help in preparing my proposal , please point me to the IRC channel or anything like Gitter etc. So ,that i can post and get reply about my queries as early as i can. Thank You for your help..

**Comment by GDLMadushanka** [comment]
@shana Hi I saw someone has started developing this feature in https://github.com/github/VisualStudio/issues/223
So is this project still a viable option ?

**Comment by shana** [comment]
@GDLMadushanka Not sure what you mean by developing the feature. That issue is where discussion happens for the feature, so people are asking questions there, that's how it works. Unless someone does a PR with the feature in advance stages of completion before GSoC starts (not likely), this issue is going to be in GSoC.

Note: In GSoC, students submit their proposals to the organization via the GSoC website. These proposals are private, and we'll evaluate them by their merits. To make your proposal, you're free to ask any questions you need and clarify anything through the issue or the chat, we're happy to help! How much the student has engaged with the project and the community is also important, we're looking for new potential long-time OSS contributors, not just a one-time thing, so that's something to be aware of.

**Comment by GDLMadushanka** [comment]
Hi @shana Thanks for the reply. I read a little about architecture of Git (DAG like stuff), Cloned the repo and started learning about other projects that the main project depends on. And I planned of doing some "getting start" type projects on Akavache, LibGit2Sharp, Octokit, ReactiveUI and Rothko (To understand Facade layers). It would be really helpful if you could give some guidelines on how to get things started.

**Comment by shana** [comment]
@GDLMadushanka If you've never created visual studio extensions before, that's probably a good way to start, so you can understand how to host UI in visual studio and how things are different from a standalone application. There's various templates in Visual Studio for creating extensions, and examples on msdn and other sites. The more important external libraries for this project are going to be Octokit (GitHub API) and ReactiveUI (for building the UI). Understanding Reactive extensions will also be useful, as our code uses a lot of reactive stuff.

**Comment by GDLMadushanka** [comment]
@shana can we send our applications prior to submission period ?. Then we can take feedback and improve them. If yes, please provide some method to contact you. Thanks.

**Comment by shana** [comment]
@GDLMadushanka There will be plenty of time to take feedback during the application period, no need to send things before then.

**Comment by GDLMadushanka** [comment]
@shana It's only 4 days remaining till final proposal submission. My proposal didn't get any comments to make improvements. Can you please look into that. Thanks.
